// Auto-generated from FIFA 2026 squad lists
// Cutoff para Mejor Joven: nacidos después del 11/6/2005

export const JUGADORES = {
  'Alemania': [
    { nombre: 'NEUER Manuel', pos: 'PO', joven: false, portero: true },
    { nombre: 'RUEDIGER Antonio', pos: 'DF', joven: false, portero: false },
    { nombre: 'ANTON Waldemar', pos: 'DF', joven: false, portero: false },
    { nombre: 'TAH Jonathan', pos: 'DF', joven: false, portero: false },
    { nombre: 'PAVLOVIC Aleksandar', pos: 'MC', joven: false, portero: false },
    { nombre: 'KIMMICH Joshua', pos: 'DF', joven: false, portero: false },
    { nombre: 'HAVERTZ Kai', pos: 'DC', joven: false, portero: false },
    { nombre: 'GORETZKA Leon', pos: 'MC', joven: false, portero: false },
    { nombre: 'LEWELING Jamie', pos: 'MC', joven: false, portero: false },
    { nombre: 'MUSIALA Jamal', pos: 'MC', joven: false, portero: false },
    { nombre: 'WOLTEMADE Nick', pos: 'DC', joven: false, portero: false },
    { nombre: 'BAUMANN Oliver', pos: 'PO', joven: false, portero: true },
    { nombre: 'GROSS Pascal', pos: 'MC', joven: false, portero: false },
    { nombre: 'BEIER Maximilian', pos: 'DC', joven: false, portero: false },
    { nombre: 'SCHLOTTERBECK Nico', pos: 'DF', joven: false, portero: false },
    { nombre: 'STILLER Angelo', pos: 'MC', joven: false, portero: false },
    { nombre: 'WIRTZ Florian', pos: 'MC', joven: false, portero: false },
    { nombre: 'BROWN Nathaniel', pos: 'DF', joven: false, portero: false },
    { nombre: 'SANE Leroy', pos: 'MC', joven: false, portero: false },
    { nombre: 'AMIRI Nadiem', pos: 'MC', joven: false, portero: false },
    { nombre: 'NUEBEL Alexander', pos: 'PO', joven: false, portero: true },
    { nombre: 'RAUM David', pos: 'DF', joven: false, portero: false },
    { nombre: 'NMECHA Felix', pos: 'MC', joven: false, portero: false },
    { nombre: 'THIAW Malick', pos: 'DF', joven: false, portero: false },
    { nombre: 'KARL Lennart', pos: 'MC', joven: true, portero: false },
    { nombre: 'UNDAV Deniz', pos: 'DC', joven: false, portero: false },
  ],
  'Arabia Saudí': [
    { nombre: 'NAWAF ALAQIDI', pos: 'PO', joven: false, portero: true },
    { nombre: 'ALI MAJRASHI', pos: 'DF', joven: false, portero: false },
    { nombre: 'ALI LAJAMI', pos: 'DF', joven: false, portero: false },
    { nombre: 'ABDULELAH ALAMRI', pos: 'DF', joven: false, portero: false },
    { nombre: 'HASSAN ALTAMBAKTI', pos: 'DF', joven: false, portero: false },
    { nombre: 'NASSER ALDAWSARI', pos: 'MC', joven: false, portero: false },
    { nombre: 'MUSAB ALJUWAYR', pos: 'MC', joven: false, portero: false },
    { nombre: 'AIMAN YAHYA', pos: 'DC', joven: false, portero: false },
    { nombre: 'FERAS ALBRIKAN', pos: 'DC', joven: false, portero: false },
    { nombre: 'SALEM ALDAWSARI', pos: 'DC', joven: false, portero: false },
    { nombre: 'SALEH ALSHEHRI', pos: 'DC', joven: false, portero: false },
    { nombre: 'SAUD ABDULHAMID', pos: 'DF', joven: false, portero: false },
    { nombre: 'NAWAF BU WASHL', pos: 'DF', joven: false, portero: false },
    { nombre: 'HASSAN KADISH', pos: 'DF', joven: false, portero: false },
    { nombre: 'ABDULLAH ALKHAIBARI', pos: 'MC', joven: false, portero: false },
    { nombre: 'ZIYAD ALJOHANI', pos: 'MC', joven: false, portero: false },
    { nombre: 'KHALID ALGHANNAM', pos: 'DC', joven: false, portero: false },
    { nombre: 'ALA ALHAJJI', pos: 'MC', joven: false, portero: false },
    { nombre: 'ABDULLAH ALHAMDDAN', pos: 'DC', joven: false, portero: false },
    { nombre: 'SULTAN MANDASH', pos: 'DC', joven: false, portero: false },
    { nombre: 'MOHAMMED ALOWAIS', pos: 'PO', joven: false, portero: true },
    { nombre: 'AHMED ALKASSAR', pos: 'PO', joven: false, portero: true },
    { nombre: 'MOHAMED KANNO', pos: 'MC', joven: false, portero: false },
    { nombre: 'MOTEB ALHARBI', pos: 'DF', joven: false, portero: false },
    { nombre: 'JEHAD THIKRI', pos: 'DF', joven: false, portero: false },
    { nombre: 'MOHAMMED ABU ALSHAMAT', pos: 'DF', joven: false, portero: false },
  ],
  'Argelia': [
    { nombre: 'MASTIL Melvin', pos: 'PO', joven: false, portero: true },
    { nombre: 'MANDI Aissa', pos: 'DF', joven: false, portero: false },
    { nombre: 'ABADA Achraf', pos: 'DF', joven: false, portero: false },
    { nombre: 'TOUGAI Mohamed Amine', pos: 'DF', joven: false, portero: false },
    { nombre: 'BELAID Zineddine', pos: 'DF', joven: false, portero: false },
    { nombre: 'ZERROUKI Ramiz', pos: 'MC', joven: false, portero: false },
    { nombre: 'MAHREZ Riyad', pos: 'DC', joven: false, portero: false },
    { nombre: 'AOUAR Houssem', pos: 'MC', joven: false, portero: false },
    { nombre: 'GOUIRI Amine', pos: 'DC', joven: false, portero: false },
    { nombre: 'CHAIBI Fares', pos: 'MC', joven: false, portero: false },
    { nombre: 'HADJ MOUSSA Anis', pos: 'DC', joven: false, portero: false },
    { nombre: 'BENBOUALI Nadhir', pos: 'DC', joven: false, portero: false },
    { nombre: 'HADJAM Jaouen', pos: 'DF', joven: false, portero: false },
    { nombre: 'BOUDAOUI Hicham', pos: 'MC', joven: false, portero: false },
    { nombre: 'AIT-NOURI Rayan', pos: 'DF', joven: false, portero: false },
    { nombre: 'BENBOT Oussama', pos: 'PO', joven: false, portero: true },
    { nombre: 'BELGHALI Rak', pos: 'DF', joven: false, portero: false },
    { nombre: 'AMOURA Mohamed', pos: 'DC', joven: false, portero: false },
    { nombre: 'BENTALEB Nabil', pos: 'MC', joven: false, portero: false },
    { nombre: 'BOULBINA Adil', pos: 'DC', joven: false, portero: false },
    { nombre: 'BENSEBAINI Ramy', pos: 'DF', joven: false, portero: false },
    { nombre: 'MAZA Ibrahim', pos: 'MC', joven: true, portero: false },
    { nombre: 'ZIDANE Luca', pos: 'PO', joven: false, portero: true },
    { nombre: 'TITRAOUI Yassine', pos: 'MC', joven: false, portero: false },
    { nombre: 'GHEDJEMIS Fares', pos: 'DC', joven: false, portero: false },
    { nombre: 'CHERGUI Samir', pos: 'DF', joven: false, portero: false },
  ],
  'Argentina': [
    { nombre: 'MUSSO Juan', pos: 'PO', joven: false, portero: true },
    { nombre: 'BALERDI Leonardo', pos: 'DF', joven: false, portero: false },
    { nombre: 'TAGLIAFICO Nicolas', pos: 'DF', joven: false, portero: false },
    { nombre: 'MONTIEL Gonzalo', pos: 'DF', joven: false, portero: false },
    { nombre: 'PAREDES Leandro', pos: 'MC', joven: false, portero: false },
    { nombre: 'MARTINEZ Lisandro', pos: 'DF', joven: false, portero: false },
    { nombre: 'DE PAUL Rodrigo', pos: 'MC', joven: false, portero: false },
    { nombre: 'BARCO Valentin', pos: 'MC', joven: false, portero: false },
    { nombre: 'ALVAREZ Julian', pos: 'DC', joven: false, portero: false },
    { nombre: 'MESSI Lionel', pos: 'DC', joven: false, portero: false },
    { nombre: 'LO CELSO Giovani', pos: 'MC', joven: false, portero: false },
    { nombre: 'RULLI Geronimo', pos: 'PO', joven: false, portero: true },
    { nombre: 'ROMERO Cristian', pos: 'DF', joven: false, portero: false },
    { nombre: 'PALACIOS Exequiel', pos: 'MC', joven: false, portero: false },
    { nombre: 'GONZALEZ Nico', pos: 'MC', joven: false, portero: false },
    { nombre: 'ALMADA Thiago', pos: 'DC', joven: false, portero: false },
    { nombre: 'SIMEONE Giuliano', pos: 'DC', joven: false, portero: false },
    { nombre: 'PAZ Nico', pos: 'DC', joven: false, portero: false },
    { nombre: 'OTAMENDI Nicolas', pos: 'DF', joven: false, portero: false },
    { nombre: 'MAC ALLISTER Alexis', pos: 'MC', joven: false, portero: false },
    { nombre: 'LOPEZ Jose Manuel', pos: 'DC', joven: false, portero: false },
    { nombre: 'MARTINEZ Lautaro', pos: 'DC', joven: false, portero: false },
    { nombre: 'MARTINEZ Emiliano', pos: 'PO', joven: false, portero: true },
    { nombre: 'FERNANDEZ Enzo', pos: 'MC', joven: false, portero: false },
    { nombre: 'MEDINA Facundo', pos: 'DF', joven: false, portero: false },
    { nombre: 'MOLINA Nahuel', pos: 'DF', joven: false, portero: false },
  ],
  'Australia': [
    { nombre: 'RYAN Mathew', pos: 'PO', joven: false, portero: true },
    { nombre: 'DEGENEK Milos', pos: 'DF', joven: false, portero: false },
    { nombre: 'CIRCATI Alessandro', pos: 'DF', joven: false, portero: false },
    { nombre: 'ITALIANO Jacob', pos: 'DF', joven: false, portero: false },
    { nombre: 'BOS Jordan', pos: 'DF', joven: false, portero: false },
    { nombre: 'GERIA Jason', pos: 'DF', joven: false, portero: false },
    { nombre: 'LECKIE Mathew', pos: 'DC', joven: false, portero: false },
    { nombre: 'METCALFE Connor', pos: 'MC', joven: false, portero: false },
    { nombre: 'TOURE Mohamed', pos: 'DC', joven: false, portero: false },
    { nombre: 'HRUSTIC Ajdin', pos: 'DC', joven: false, portero: false },
    { nombre: 'MABIL Awer', pos: 'DC', joven: false, portero: false },
    { nombre: 'IZZO Paul', pos: 'PO', joven: false, portero: true },
    { nombre: 'ONEILL Aiden', pos: 'MC', joven: false, portero: false },
    { nombre: 'DEVLIN Cameron', pos: 'MC', joven: false, portero: false },
    { nombre: 'TREWIN Kai', pos: 'DF', joven: false, portero: false },
    { nombre: 'BEHICH Aziz', pos: 'DF', joven: false, portero: false },
    { nombre: 'IRANKUNDA Nestory', pos: 'DC', joven: true, portero: false },
    { nombre: 'BEACH Patrick', pos: 'PO', joven: false, portero: true },
    { nombre: 'SOUTTAR Harry', pos: 'DF', joven: false, portero: false },
    { nombre: 'VOLPATO Cristian', pos: 'DC', joven: false, portero: false },
    { nombre: 'BURGESS Cameron', pos: 'DF', joven: false, portero: false },
    { nombre: 'IRVINE Jackson', pos: 'MC', joven: false, portero: false },
    { nombre: 'VELUPILLAY Nishan', pos: 'DC', joven: false, portero: false },
    { nombre: 'OKON-ENGSTLER Paul', pos: 'MC', joven: false, portero: false },
    { nombre: 'HERRINGTON Lucas', pos: 'DF', joven: true, portero: false },
    { nombre: 'YENGI Tete', pos: 'DC', joven: false, portero: false },
  ],
  'Austria': [
    { nombre: 'SCHLAGER Alexander', pos: 'PO', joven: false, portero: true },
    { nombre: 'AFFENGRUBER David', pos: 'DF', joven: false, portero: false },
    { nombre: 'DANSO Kevin', pos: 'DF', joven: false, portero: false },
    { nombre: 'SCHLAGER Xaver', pos: 'MC', joven: false, portero: false },
    { nombre: 'POSCH Stefan', pos: 'DF', joven: false, portero: false },
    { nombre: 'SEIWALD Nicolas', pos: 'MC', joven: false, portero: false },
    { nombre: 'ARNAUTOVIC Marko', pos: 'DC', joven: false, portero: false },
    { nombre: 'ALABA David', pos: 'DF', joven: false, portero: false },
    { nombre: 'SABITZER Marcel', pos: 'MC', joven: false, portero: false },
    { nombre: 'GRILLITSCH Florian', pos: 'MC', joven: false, portero: false },
    { nombre: 'GREGORITSCH Michael', pos: 'DC', joven: false, portero: false },
    { nombre: 'WIEGELE Florian', pos: 'PO', joven: false, portero: true },
    { nombre: 'PENTZ Patrick', pos: 'PO', joven: false, portero: true },
    { nombre: 'KALAJDZIC Sasa', pos: 'DC', joven: false, portero: false },
    { nombre: 'LIENHART Philipp', pos: 'DF', joven: false, portero: false },
    { nombre: 'MWENE Phillip', pos: 'DF', joven: false, portero: false },
    { nombre: 'CHUKWUEMEKA Carney', pos: 'MC', joven: false, portero: false },
    { nombre: 'SCHMID Romano', pos: 'MC', joven: false, portero: false },
    { nombre: 'BAUMGARTNER Christoph', pos: 'MC', joven: false, portero: false },
    { nombre: 'LAIMER Konrad', pos: 'MC', joven: false, portero: false },
    { nombre: 'WIMMER Patrick', pos: 'DC', joven: false, portero: false },
    { nombre: 'PRASS Alexander', pos: 'MC', joven: false, portero: false },
    { nombre: 'FRIEDL Marco', pos: 'DF', joven: false, portero: false },
    { nombre: 'WANNER Paul', pos: 'MC', joven: true, portero: false },
    { nombre: 'SVOBODA Michael', pos: 'DF', joven: false, portero: false },
    { nombre: 'SCHOEPF Alessandro', pos: 'MC', joven: false, portero: false },
  ],
  'Bosnia y Herzegovina': [
    { nombre: 'VASILJ Nikola', pos: 'PO', joven: false, portero: true },
    { nombre: 'MUJAKIC Nihad', pos: 'DF', joven: false, portero: false },
    { nombre: 'HADZIKADUNIC Dennis', pos: 'DF', joven: false, portero: false },
    { nombre: 'MUHAREMOVIC Tarik', pos: 'DF', joven: false, portero: false },
    { nombre: 'KOLASINAC Sead', pos: 'DF', joven: false, portero: false },
    { nombre: 'TAHIROVIC Benjamin', pos: 'MC', joven: false, portero: false },
    { nombre: 'DEDIC Amar', pos: 'DF', joven: false, portero: false },
    { nombre: 'GIGOVIC Armin', pos: 'MC', joven: false, portero: false },
    { nombre: 'BAZDAR Samed', pos: 'DC', joven: false, portero: false },
    { nombre: 'DEMIROVIC Ermedin', pos: 'DC', joven: false, portero: false },
    { nombre: 'DZEKO Edin', pos: 'DC', joven: false, portero: false },
    { nombre: 'JURKAS Mladen', pos: 'PO', joven: true, portero: true },
    { nombre: 'BASIC Ivan', pos: 'MC', joven: false, portero: false },
    { nombre: 'SUNJIC Ivan', pos: 'MC', joven: false, portero: false },
    { nombre: 'MEMIC Amar', pos: 'MC', joven: false, portero: false },
    { nombre: 'HADZIAHMETOVIC Amir', pos: 'MC', joven: false, portero: false },
    { nombre: 'BURNIC Dzenis', pos: 'MC', joven: false, portero: false },
    { nombre: 'KATIC Nikola', pos: 'DF', joven: false, portero: false },
    { nombre: 'ALAJBEGOVIC Kerim', pos: 'DC', joven: true, portero: false },
    { nombre: 'BAJRAKTAREVIC Esmir', pos: 'DC', joven: false, portero: false },
    { nombre: 'RADELJIC Stjepan', pos: 'DF', joven: false, portero: false },
    { nombre: 'ZLOMISLIC Martin', pos: 'PO', joven: false, portero: true },
    { nombre: 'TABAKOVIC Haris', pos: 'DC', joven: false, portero: false },
    { nombre: 'CELIK Nidal', pos: 'DF', joven: true, portero: false },
    { nombre: 'LUKIC Jovo', pos: 'DC', joven: false, portero: false },
    { nombre: 'MAHMIC Ermin', pos: 'MC', joven: false, portero: false },
  ],
  'Brasil': [
    { nombre: 'ALISSON', pos: 'PO', joven: false, portero: true },
    { nombre: 'WESLEY', pos: 'DF', joven: false, portero: false },
    { nombre: 'GABRIEL MAGALHAES', pos: 'DF', joven: false, portero: false },
    { nombre: 'MARQUINHOS', pos: 'DF', joven: false, portero: false },
    { nombre: 'CASEMIRO', pos: 'MC', joven: false, portero: false },
    { nombre: 'ALEX SANDRO', pos: 'DF', joven: false, portero: false },
    { nombre: 'VINICIUS JUNIOR', pos: 'DC', joven: false, portero: false },
    { nombre: 'BRUNO GUIMARAES', pos: 'MC', joven: false, portero: false },
    { nombre: 'MATHEUS CUNHA', pos: 'DC', joven: false, portero: false },
    { nombre: 'NEYMAR JR', pos: 'DC', joven: false, portero: false },
    { nombre: 'RAPHINHA', pos: 'DC', joven: false, portero: false },
    { nombre: 'WEVERTON', pos: 'PO', joven: false, portero: true },
    { nombre: 'DANILO', pos: 'DF', joven: false, portero: false },
    { nombre: 'BREMER', pos: 'DF', joven: false, portero: false },
    { nombre: 'LEO PEREIRA', pos: 'DF', joven: false, portero: false },
    { nombre: 'DOUGLAS SANTOS', pos: 'DF', joven: false, portero: false },
    { nombre: 'FABINHO', pos: 'MC', joven: false, portero: false },
    { nombre: 'DANILO SANTOS', pos: 'MC', joven: false, portero: false },
    { nombre: 'ENDRICK', pos: 'DC', joven: true, portero: false },
    { nombre: 'LUCAS PAQUETA', pos: 'MC', joven: false, portero: false },
    { nombre: 'LUIZ HENRIQUE', pos: 'DC', joven: false, portero: false },
    { nombre: 'GABRIEL MARTINELLI', pos: 'DC', joven: false, portero: false },
    { nombre: 'EDERSON', pos: 'PO', joven: false, portero: true },
    { nombre: 'ROGER IBANEZ', pos: 'DF', joven: false, portero: false },
    { nombre: 'IGOR THIAGO', pos: 'DC', joven: false, portero: false },
    { nombre: 'RAYAN', pos: 'DC', joven: true, portero: false },
  ],
  'Bélgica': [
    { nombre: 'COURTOIS Thibaut', pos: 'PO', joven: false, portero: true },
    { nombre: 'DEBAST Zeno', pos: 'DF', joven: false, portero: false },
    { nombre: 'THEATE Arthur', pos: 'DF', joven: false, portero: false },
    { nombre: 'MECHELE Brandon', pos: 'DF', joven: false, portero: false },
    { nombre: 'DE CUYPER Maxim', pos: 'DF', joven: false, portero: false },
    { nombre: 'WITSEL Axel', pos: 'MC', joven: false, portero: false },
    { nombre: 'DE BRUYNE Kevin', pos: 'MC', joven: false, portero: false },
    { nombre: 'TIELEMANS Youri', pos: 'MC', joven: false, portero: false },
    { nombre: 'LUKAKU Romelu', pos: 'DC', joven: false, portero: false },
    { nombre: 'TROSSARD Leandro', pos: 'DC', joven: false, portero: false },
    { nombre: 'DOKU Jeremy', pos: 'DC', joven: false, portero: false },
    { nombre: 'LAMMENS Senne', pos: 'PO', joven: false, portero: true },
    { nombre: 'PENDERS Mike', pos: 'PO', joven: true, portero: true },
    { nombre: 'LUKEBAKIO Dodi', pos: 'DC', joven: false, portero: false },
    { nombre: 'MEUNIER Thomas', pos: 'DF', joven: false, portero: false },
    { nombre: 'DE WINTER Koni', pos: 'DF', joven: false, portero: false },
    { nombre: 'DE KETELAERE Charles', pos: 'DC', joven: false, portero: false },
    { nombre: 'SEYS Joaquin', pos: 'DF', joven: false, portero: false },
    { nombre: 'MOREIRA Diego', pos: 'MC', joven: false, portero: false },
    { nombre: 'VANAKEN Hans', pos: 'MC', joven: false, portero: false },
    { nombre: 'CASTAGNE Timothy', pos: 'DF', joven: false, portero: false },
    { nombre: 'SAELEMAEKERS Alexis', pos: 'MC', joven: false, portero: false },
    { nombre: 'RASKIN Nicolas', pos: 'MC', joven: false, portero: false },
    { nombre: 'ONANA Amadou', pos: 'MC', joven: false, portero: false },
    { nombre: 'NGOY Nathan', pos: 'DF', joven: false, portero: false },
    { nombre: 'FERNANDEZ-PARDO Matias', pos: 'DC', joven: false, portero: false },
  ],
  'Cabo Verde': [
    { nombre: 'VOZINHA', pos: 'PO', joven: false, portero: true },
    { nombre: 'STOPIRA', pos: 'DF', joven: false, portero: false },
    { nombre: 'DINEY BORGES', pos: 'DF', joven: false, portero: false },
    { nombre: 'PICO LOPES', pos: 'DF', joven: false, portero: false },
    { nombre: 'LOGAN COSTA', pos: 'DF', joven: false, portero: false },
    { nombre: 'KEVIN PINA', pos: 'MC', joven: false, portero: false },
    { nombre: 'JOVANE CABRAL', pos: 'MC', joven: false, portero: false },
    { nombre: 'JOAO PAULO', pos: 'MC', joven: false, portero: false },
    { nombre: 'GILSON BENCHIMOL', pos: 'DC', joven: false, portero: false },
    { nombre: 'JAMIRO MONTEIRO', pos: 'MC', joven: false, portero: false },
    { nombre: 'GARRY RODRIGUES', pos: 'MC', joven: false, portero: false },
    { nombre: 'MARCIO ROSA', pos: 'PO', joven: false, portero: true },
    { nombre: 'SIDNY LOPES CABRAL', pos: 'DF', joven: false, portero: false },
    { nombre: 'DEROY DUARTE', pos: 'MC', joven: false, portero: false },
    { nombre: 'LAROS DUARTE', pos: 'MC', joven: false, portero: false },
    { nombre: 'YANNICK SEMEDO', pos: 'MC', joven: false, portero: false },
    { nombre: 'WILLY SEMEDO', pos: 'MC', joven: false, portero: false },
    { nombre: 'TELMO ARCANJO', pos: 'MC', joven: false, portero: false },
    { nombre: 'DAILON LIVRAMENTO', pos: 'DC', joven: false, portero: false },
    { nombre: 'RYAN MENDES', pos: 'DC', joven: false, portero: false },
    { nombre: 'NUNO DA COSTA', pos: 'MC', joven: false, portero: false },
    { nombre: 'STEVEN MOREIRA', pos: 'DF', joven: false, portero: false },
    { nombre: 'CJ DOS SANTOS', pos: 'PO', joven: false, portero: true },
    { nombre: 'WAGNER PINA', pos: 'DF', joven: false, portero: false },
    { nombre: 'KELVIN PIRES', pos: 'DF', joven: false, portero: false },
    { nombre: 'HELIO VARELA', pos: 'MC', joven: false, portero: false },
  ],
  'Canadá': [
    { nombre: 'ST. CLAIR Dayne', pos: 'PO', joven: false, portero: true },
    { nombre: 'JOHNSTON Alistair', pos: 'DF', joven: false, portero: false },
    { nombre: 'JONES Ale', pos: 'DF', joven: false, portero: false },
    { nombre: 'DE FOUGEROLLES Luc', pos: 'DF', joven: true, portero: false },
    { nombre: 'WATERMAN Joel', pos: 'DF', joven: false, portero: false },
    { nombre: 'CHOINIERE Mathieu', pos: 'MC', joven: false, portero: false },
    { nombre: 'EUSTAQUIO Stephen', pos: 'MC', joven: false, portero: false },
    { nombre: 'KONE Ismael', pos: 'MC', joven: false, portero: false },
    { nombre: 'LARIN Cyle', pos: 'DC', joven: false, portero: false },
    { nombre: 'DAVID Jonathan', pos: 'DC', joven: false, portero: false },
    { nombre: 'MILLAR Liam', pos: 'MC', joven: false, portero: false },
    { nombre: 'OLUWASEYI Tani', pos: 'DC', joven: false, portero: false },
    { nombre: 'CORNELIUS Derek', pos: 'DF', joven: false, portero: false },
    { nombre: 'SHAFFELBURG Jacob', pos: 'MC', joven: false, portero: false },
    { nombre: 'BOMBITO Moise', pos: 'DF', joven: false, portero: false },
    { nombre: 'CREPEAU Maxime', pos: 'PO', joven: false, portero: true },
    { nombre: 'BUCHANAN Tajon', pos: 'DC', joven: false, portero: false },
    { nombre: 'GOODMAN Owen', pos: 'PO', joven: false, portero: true },
    { nombre: 'DAVIES Alphonso', pos: 'DF', joven: false, portero: false },
    { nombre: 'AHMED Ali', pos: 'DC', joven: false, portero: false },
    { nombre: 'OSORIO Jonathan', pos: 'MC', joven: false, portero: false },
    { nombre: 'LARYEA Richie', pos: 'DF', joven: false, portero: false },
    { nombre: 'SIGUR Niko', pos: 'DF', joven: false, portero: false },
    { nombre: 'DAVID Promise', pos: 'DC', joven: false, portero: false },
    { nombre: 'SALIBA Nathan', pos: 'MC', joven: false, portero: false },
    { nombre: 'FLORES Marcelo', pos: 'MC', joven: false, portero: false },
  ],
  'Catar': [
    { nombre: 'MAHMOUD ABUNADA', pos: 'PO', joven: false, portero: true },
    { nombre: 'PEDRO MIGUEL', pos: 'DF', joven: false, portero: false },
    { nombre: 'LUCAS MENDES', pos: 'DF', joven: false, portero: false },
    { nombre: 'ISSA LAYE', pos: 'DF', joven: false, portero: false },
    { nombre: 'JASSEM GABER', pos: 'DF', joven: false, portero: false },
    { nombre: 'ABDULAZIZ HATEM', pos: 'MC', joven: false, portero: false },
    { nombre: 'AHMED ALAAELDIN', pos: 'DC', joven: false, portero: false },
    { nombre: 'EDMILSON JUNIOR', pos: 'DC', joven: false, portero: false },
    { nombre: 'MOHAMMED MUNTARI', pos: 'DC', joven: false, portero: false },
    { nombre: 'HASSAN ALHAYDOS', pos: 'DC', joven: false, portero: false },
    { nombre: 'AKRAM AFIF', pos: 'DC', joven: false, portero: false },
    { nombre: 'KARIM BOUDIAF', pos: 'MC', joven: false, portero: false },
    { nombre: 'AYOUB ALOUI', pos: 'DF', joven: false, portero: false },
    { nombre: 'HOMAM AHMED', pos: 'DF', joven: false, portero: false },
    { nombre: 'YUSUF ABDURISAG', pos: 'DC', joven: false, portero: false },
    { nombre: 'BOUALEM KHOUKHI', pos: 'DF', joven: false, portero: false },
    { nombre: 'AHMED ALGANEHI', pos: 'MC', joven: false, portero: false },
    { nombre: 'SULTAN ALBRAKE', pos: 'DF', joven: false, portero: false },
    { nombre: 'ALMOEZ ALI', pos: 'DC', joven: false, portero: false },
    { nombre: 'AHMED FATHY', pos: 'MC', joven: false, portero: false },
    { nombre: 'SALAH ZAKARIA', pos: 'PO', joven: false, portero: true },
    { nombre: 'MESHAAL BARSHAM', pos: 'PO', joven: false, portero: true },
    { nombre: 'ASSIM MADIBO', pos: 'MC', joven: false, portero: false },
    { nombre: 'TAHSIN JAMSHID', pos: 'DC', joven: true, portero: false },
    { nombre: 'ALHASHMI ALHUSSEIN', pos: 'DF', joven: false, portero: false },
    { nombre: 'MOHAMED MANAI', pos: 'DC', joven: false, portero: false },
  ],
  'Colombia': [
    { nombre: 'OSPINA David', pos: 'PO', joven: false, portero: true },
    { nombre: 'MUNOZ Daniel', pos: 'DF', joven: false, portero: false },
    { nombre: 'LUCUMI Jhon', pos: 'DF', joven: false, portero: false },
    { nombre: 'ARIAS Santiago', pos: 'DF', joven: false, portero: false },
    { nombre: 'CASTANO Kevin', pos: 'MC', joven: false, portero: false },
    { nombre: 'RIOS Richard', pos: 'MC', joven: false, portero: false },
    { nombre: 'DIAZ Luis', pos: 'DC', joven: false, portero: false },
    { nombre: 'CARRASCAL Jorge', pos: 'MC', joven: false, portero: false },
    { nombre: 'CORDOBA Jhon', pos: 'DC', joven: false, portero: false },
    { nombre: 'RODRIGUEZ James', pos: 'MC', joven: false, portero: false },
    { nombre: 'ARIAS Jhon', pos: 'MC', joven: false, portero: false },
    { nombre: 'VARGAS Camilo', pos: 'PO', joven: false, portero: true },
    { nombre: 'MINA Yerry', pos: 'DF', joven: false, portero: false },
    { nombre: 'PUERTA Gustavo', pos: 'DF', joven: false, portero: false },
    { nombre: 'PORTILLA Juan', pos: 'MC', joven: false, portero: false },
    { nombre: 'LERMA Jefferson', pos: 'MC', joven: false, portero: false },
    { nombre: 'MOJICA Johan', pos: 'DF', joven: false, portero: false },
    { nombre: 'DITTA Willer', pos: 'DF', joven: false, portero: false },
    { nombre: 'HERNANDEZ Cucho', pos: 'DC', joven: false, portero: false },
    { nombre: 'QUINTERO Juan', pos: 'MC', joven: false, portero: false },
    { nombre: 'CAMPAZ Jaminton', pos: 'DC', joven: false, portero: false },
    { nombre: 'MACHADO Deiver', pos: 'DF', joven: false, portero: false },
    { nombre: 'SANCHEZ Davinson', pos: 'DF', joven: false, portero: false },
    { nombre: 'MONTERO Alvaro', pos: 'PO', joven: false, portero: true },
    { nombre: 'SUAREZ Luis', pos: 'DC', joven: false, portero: false },
    { nombre: 'GOMEZ Andres', pos: 'DC', joven: false, portero: false },
  ],
  'Corea del Sur': [
    { nombre: 'KIM Seunggyu', pos: 'PO', joven: false, portero: true },
    { nombre: 'LEE Hanbeom', pos: 'DF', joven: false, portero: false },
    { nombre: 'LEE Gihyuk', pos: 'MC', joven: false, portero: false },
    { nombre: 'KIM Minjae', pos: 'DF', joven: false, portero: false },
    { nombre: 'KIM Taehyeon', pos: 'DF', joven: false, portero: false },
    { nombre: 'HWANG Inbeom', pos: 'MC', joven: false, portero: false },
    { nombre: 'SON Heungmin', pos: 'DC', joven: false, portero: false },
    { nombre: 'PAIK Seungho', pos: 'MC', joven: false, portero: false },
    { nombre: 'CHO Guesung', pos: 'DC', joven: false, portero: false },
    { nombre: 'LEE Jaesung', pos: 'MC', joven: false, portero: false },
    { nombre: 'HWANG Heechan', pos: 'MC', joven: false, portero: false },
    { nombre: 'SONG Bumkeun', pos: 'PO', joven: false, portero: true },
    { nombre: 'LEE Taeseok', pos: 'DF', joven: false, portero: false },
    { nombre: 'CHO Wije', pos: 'DF', joven: false, portero: false },
    { nombre: 'KIM Moonhwan', pos: 'DF', joven: false, portero: false },
    { nombre: 'PARK Jinseob', pos: 'DF', joven: false, portero: false },
    { nombre: 'BAE Junho', pos: 'MC', joven: false, portero: false },
    { nombre: 'OH Hyeongyu', pos: 'DC', joven: false, portero: false },
    { nombre: 'LEE Kangin', pos: 'MC', joven: false, portero: false },
    { nombre: 'YANG Hyunjun', pos: 'MC', joven: false, portero: false },
    { nombre: 'JO Hyeonwoo', pos: 'PO', joven: false, portero: true },
    { nombre: 'SEOL Youngwoo', pos: 'DF', joven: false, portero: false },
    { nombre: 'CASTROP Jens', pos: 'DF', joven: false, portero: false },
    { nombre: 'KIM Jingyu', pos: 'MC', joven: false, portero: false },
    { nombre: 'EOM Jisung', pos: 'MC', joven: false, portero: false },
    { nombre: 'LEE Donggyeong', pos: 'MC', joven: false, portero: false },
  ],
  'Costa de Marfil': [
    { nombre: 'FOFANA Yahia', pos: 'PO', joven: false, portero: true },
    { nombre: 'DIOMANDE Ousmane', pos: 'DF', joven: false, portero: false },
    { nombre: 'KONAN Ghislain', pos: 'DF', joven: false, portero: false },
    { nombre: 'SERI Jean Michael', pos: 'MC', joven: false, portero: false },
    { nombre: 'SINGO Wilfried', pos: 'DF', joven: false, portero: false },
    { nombre: 'FOFANA Seko', pos: 'MC', joven: false, portero: false },
    { nombre: 'KOSSOUNOU Odilon', pos: 'DF', joven: false, portero: false },
    { nombre: 'KESSIE Franck', pos: 'MC', joven: false, portero: false },
    { nombre: 'BONNY Ange-Yoan', pos: 'DC', joven: false, portero: false },
    { nombre: 'ADINGRA Simon', pos: 'DC', joven: false, portero: false },
    { nombre: 'DIOMANDE Yan', pos: 'DC', joven: true, portero: false },
    { nombre: 'WAHI Elye', pos: 'DC', joven: false, portero: false },
    { nombre: 'OPERI Christopher', pos: 'DF', joven: false, portero: false },
    { nombre: 'DIAKITE Oumar', pos: 'DC', joven: false, portero: false },
    { nombre: 'DIALLO Amad', pos: 'DC', joven: false, portero: false },
    { nombre: 'KONE Mohamed', pos: 'PO', joven: false, portero: true },
    { nombre: 'DOUE Guela', pos: 'DF', joven: false, portero: false },
    { nombre: 'SANGARE Ibrahim', pos: 'MC', joven: false, portero: false },
    { nombre: 'PEPE Nicolas', pos: 'DC', joven: false, portero: false },
    { nombre: 'AGBADOU Emmanuel', pos: 'DF', joven: false, portero: false },
    { nombre: 'NDICKA Evan', pos: 'DF', joven: false, portero: false },
    { nombre: 'GUESSAND Evann', pos: 'DC', joven: false, portero: false },
    { nombre: 'LAFONT Alban', pos: 'PO', joven: false, portero: true },
    { nombre: 'TOURE Bazoumana', pos: 'DC', joven: true, portero: false },
    { nombre: 'GUIAGON Parfait', pos: 'MC', joven: false, portero: false },
    { nombre: 'OULAI Christ', pos: 'MC', joven: true, portero: false },
  ],
  'Croacia': [
    { nombre: 'LIVAKOVIC Dominik', pos: 'PO', joven: false, portero: true },
    { nombre: 'STANISIC Josip', pos: 'DF', joven: false, portero: false },
    { nombre: 'PONGRACIC Marin', pos: 'DF', joven: false, portero: false },
    { nombre: 'GVARDIOL Josko', pos: 'DF', joven: false, portero: false },
    { nombre: 'CALETA-CAR Duje', pos: 'DF', joven: false, portero: false },
    { nombre: 'SUTALO Josip', pos: 'DF', joven: false, portero: false },
    { nombre: 'MORO Nikola', pos: 'MC', joven: false, portero: false },
    { nombre: 'KOVACIC Mateo', pos: 'MC', joven: false, portero: false },
    { nombre: 'KRAMARIC Andrej', pos: 'DC', joven: false, portero: false },
    { nombre: 'MODRIC Luka', pos: 'MC', joven: false, portero: false },
    { nombre: 'BUDIMIR Ante', pos: 'DC', joven: false, portero: false },
    { nombre: 'PANDUR Ivor', pos: 'PO', joven: false, portero: true },
    { nombre: 'VLASIC Nikola', pos: 'MC', joven: false, portero: false },
    { nombre: 'PERISIC Ivan', pos: 'DC', joven: false, portero: false },
    { nombre: 'PASALIC Mario', pos: 'MC', joven: false, portero: false },
    { nombre: 'BATURINA Martin', pos: 'MC', joven: false, portero: false },
    { nombre: 'SUCIC Petar', pos: 'MC', joven: false, portero: false },
    { nombre: 'JAKIC Kristijan', pos: 'DF', joven: false, portero: false },
    { nombre: 'FRUK Toni', pos: 'MC', joven: false, portero: false },
    { nombre: 'MATANOVIC Igor', pos: 'DC', joven: false, portero: false },
    { nombre: 'SUCIC Luka', pos: 'MC', joven: false, portero: false },
    { nombre: 'VUSKOVIC Luka', pos: 'DF', joven: true, portero: false },
    { nombre: 'KOTARSKI Dominik', pos: 'PO', joven: false, portero: true },
    { nombre: 'PASALIC Marco', pos: 'DC', joven: false, portero: false },
    { nombre: 'ERLIC Martin', pos: 'DF', joven: false, portero: false },
    { nombre: 'MUSA Petar', pos: 'DC', joven: false, portero: false },
  ],
  'Curazao': [
    { nombre: 'ROOM Eloy', pos: 'PO', joven: false, portero: true },
    { nombre: 'SAMBO Shurandy', pos: 'DF', joven: false, portero: false },
    { nombre: 'GAARI Jurien', pos: 'DF', joven: false, portero: false },
    { nombre: 'VAN EIJMA Roshon', pos: 'DF', joven: false, portero: false },
    { nombre: 'FLORANUS Sherel', pos: 'DF', joven: false, portero: false },
    { nombre: 'ROEMERATOE Godfried', pos: 'MC', joven: false, portero: false },
    { nombre: 'BACUNA Juninho', pos: 'MC', joven: false, portero: false },
    { nombre: 'COMENENCIA Livano', pos: 'MC', joven: false, portero: false },
    { nombre: 'LOCADIA Juergen', pos: 'DC', joven: false, portero: false },
    { nombre: 'BACUNA Leandro', pos: 'MC', joven: false, portero: false },
    { nombre: 'ANTONISSE Jeremy', pos: 'DC', joven: false, portero: false },
    { nombre: 'HANSEN Sontje', pos: 'DC', joven: false, portero: false },
    { nombre: 'NOSLIN Tyrese', pos: 'DC', joven: false, portero: false },
    { nombre: 'GORRE Kenji', pos: 'DC', joven: false, portero: false },
    { nombre: 'MARTHA Arjany', pos: 'MC', joven: false, portero: false },
    { nombre: 'MARGARITHA Jearl', pos: 'DC', joven: false, portero: false },
    { nombre: 'KUWAS Brandley', pos: 'DC', joven: false, portero: false },
    { nombre: 'OBISPO Armando', pos: 'DF', joven: false, portero: false },
    { nombre: 'KASTANEER Gervane', pos: 'DC', joven: false, portero: false },
    { nombre: 'BRENET Joshua', pos: 'DF', joven: false, portero: false },
    { nombre: 'CHONG Tahith', pos: 'MC', joven: false, portero: false },
    { nombre: 'FELIDA Kevin', pos: 'MC', joven: false, portero: false },
    { nombre: 'BAZOER Riechedly', pos: 'DF', joven: false, portero: false },
    { nombre: 'FONVILLE Deveron', pos: 'DF', joven: false, portero: false },
    { nombre: 'BODAK Tyrick', pos: 'PO', joven: false, portero: true },
    { nombre: 'DOORNBUSCH Trevor', pos: 'PO', joven: false, portero: true },
  ],
  'Ecuador': [
    { nombre: 'GALINDEZ Hernan', pos: 'PO', joven: false, portero: true },
    { nombre: 'TORRES Felix', pos: 'DF', joven: false, portero: false },
    { nombre: 'HINCAPIE Piero', pos: 'DF', joven: false, portero: false },
    { nombre: 'ORDONEZ Joel', pos: 'DF', joven: false, portero: false },
    { nombre: 'ALCIVAR Jordy', pos: 'MC', joven: false, portero: false },
    { nombre: 'PACHO Willian', pos: 'DF', joven: false, portero: false },
    { nombre: 'ESTUPINAN Pervis', pos: 'DF', joven: false, portero: false },
    { nombre: 'VALENCIA Anthony', pos: 'MC', joven: false, portero: false },
    { nombre: 'YEBOAH John', pos: 'DC', joven: false, portero: false },
    { nombre: 'PAEZ Kendry', pos: 'MC', joven: true, portero: false },
    { nombre: 'RODRIGUEZ Kevin', pos: 'DC', joven: false, portero: false },
    { nombre: 'RAMIREZ Moises', pos: 'PO', joven: false, portero: true },
    { nombre: 'VALENCIA Enner', pos: 'DC', joven: false, portero: false },
    { nombre: 'MINDA Alan', pos: 'MC', joven: false, portero: false },
    { nombre: 'VITE Pedro', pos: 'MC', joven: false, portero: false },
    { nombre: 'CAICEDO Jordy', pos: 'DC', joven: false, portero: false },
    { nombre: 'PRECIADO Angelo', pos: 'DF', joven: false, portero: false },
    { nombre: 'CASTILLO Denil', pos: 'MC', joven: false, portero: false },
    { nombre: 'PLATA Gonzalo', pos: 'DC', joven: false, portero: false },
    { nombre: 'ANGULO Nilson', pos: 'DC', joven: false, portero: false },
    { nombre: 'FRANCO Alan', pos: 'MC', joven: false, portero: false },
    { nombre: 'VALLE Gonzalo', pos: 'PO', joven: false, portero: true },
    { nombre: 'CAICEDO Moises', pos: 'MC', joven: false, portero: false },
    { nombre: 'AREVALO Jeremy', pos: 'DC', joven: false, portero: false },
    { nombre: 'POROZO Jackson', pos: 'DF', joven: false, portero: false },
    { nombre: 'MEDINA Yaimar', pos: 'DF', joven: false, portero: false },
  ],
  'Egipto': [
    { nombre: 'MOHAMED ELSHENAWY', pos: 'PO', joven: false, portero: true },
    { nombre: 'YASSER IBRAHIM', pos: 'DF', joven: false, portero: false },
    { nombre: 'MOHAMED HANY', pos: 'DF', joven: false, portero: false },
    { nombre: 'HOSSAM ABDELMAGUID', pos: 'DF', joven: false, portero: false },
    { nombre: 'RAMY RABIA', pos: 'DF', joven: false, portero: false },
    { nombre: 'MOHAMED ABDELMONEIM', pos: 'DF', joven: false, portero: false },
    { nombre: 'TREZEGUET', pos: 'DC', joven: false, portero: false },
    { nombre: 'EMAM ASHOUR', pos: 'MC', joven: false, portero: false },
    { nombre: 'HAMZA ABDELKARIM', pos: 'DC', joven: true, portero: false },
    { nombre: 'MOHAMED SALAH', pos: 'DC', joven: false, portero: false },
    { nombre: 'MOSTAFA ZICO', pos: 'MC', joven: false, portero: false },
    { nombre: 'HAISSEM HASSAN', pos: 'DC', joven: false, portero: false },
    { nombre: 'AHMED FATOUH', pos: 'DF', joven: false, portero: false },
    { nombre: 'HAMDY FATHY', pos: 'MC', joven: false, portero: false },
    { nombre: 'KARIM HAFEZ', pos: 'DF', joven: false, portero: false },
    { nombre: 'MAHDY SOLIMAN', pos: 'PO', joven: false, portero: true },
    { nombre: 'MOHANAD LASHIN', pos: 'MC', joven: false, portero: false },
    { nombre: 'NABIL DONGA', pos: 'MC', joven: false, portero: false },
    { nombre: 'MARAWAN ATTIA', pos: 'MC', joven: false, portero: false },
    { nombre: 'IBRAHIM ADEL', pos: 'DC', joven: false, portero: false },
    { nombre: 'MAHMOUD SABER', pos: 'MC', joven: false, portero: false },
    { nombre: 'OMAR MARMOUSH', pos: 'DC', joven: false, portero: false },
    { nombre: 'MOSTAFA SHOUBIR', pos: 'PO', joven: false, portero: true },
    { nombre: 'TAREK ALAA', pos: 'DF', joven: false, portero: false },
    { nombre: 'ZIZO', pos: 'DC', joven: false, portero: false },
    { nombre: 'MOHAMED ALAA', pos: 'PO', joven: false, portero: true },
  ],
  'Escocia': [
    { nombre: 'GUNN Angus', pos: 'PO', joven: false, portero: true },
    { nombre: 'HICKEY Aaron', pos: 'DF', joven: false, portero: false },
    { nombre: 'ROBERTSON Andy', pos: 'DF', joven: false, portero: false },
    { nombre: 'McTOMINAY Scott', pos: 'MC', joven: false, portero: false },
    { nombre: 'HANLEY Grant', pos: 'DF', joven: false, portero: false },
    { nombre: 'TIERNEY Kieran', pos: 'DF', joven: false, portero: false },
    { nombre: 'McGINN John', pos: 'MC', joven: false, portero: false },
    { nombre: 'FLETCHER Tyler', pos: 'MC', joven: true, portero: false },
    { nombre: 'DYKES Lyndon', pos: 'DC', joven: false, portero: false },
    { nombre: 'ADAMS Che', pos: 'DC', joven: false, portero: false },
    { nombre: 'CHRISTIE Ryan', pos: 'MC', joven: false, portero: false },
    { nombre: 'KELLY Liam', pos: 'PO', joven: false, portero: true },
    { nombre: 'HENDRY Jack', pos: 'DF', joven: false, portero: false },
    { nombre: 'STEWART Ross', pos: 'DC', joven: false, portero: false },
    { nombre: 'SOUTTAR John', pos: 'DF', joven: false, portero: false },
    { nombre: 'HYAM Dominic', pos: 'DF', joven: false, portero: false },
    { nombre: 'GANNON-DOAK Ben', pos: 'DC', joven: true, portero: false },
    { nombre: 'HIRST George', pos: 'DC', joven: false, portero: false },
    { nombre: 'FERGUSON Lewis', pos: 'MC', joven: false, portero: false },
    { nombre: 'SHANKLAND Lawrence', pos: 'DC', joven: false, portero: false },
    { nombre: 'GORDON Craig', pos: 'PO', joven: false, portero: true },
    { nombre: 'PATTERSON Nathan', pos: 'DF', joven: false, portero: false },
    { nombre: 'McLEAN Kenny', pos: 'MC', joven: false, portero: false },
    { nombre: 'RALSTON Anthony', pos: 'DF', joven: false, portero: false },
    { nombre: 'CURTIS Findlay', pos: 'DC', joven: true, portero: false },
    { nombre: 'McKENNA Scott', pos: 'DF', joven: false, portero: false },
  ],
  'España': [
    { nombre: 'RAYA David', pos: 'PO', joven: false, portero: true },
    { nombre: 'PUBILL Marc', pos: 'DF', joven: false, portero: false },
    { nombre: 'GRIMALDO Alex', pos: 'DF', joven: false, portero: false },
    { nombre: 'GARCIA Eric', pos: 'DF', joven: false, portero: false },
    { nombre: 'LLORENTE Marcos', pos: 'DF', joven: false, portero: false },
    { nombre: 'MERINO Mikel', pos: 'MC', joven: false, portero: false },
    { nombre: 'TORRES Ferran', pos: 'DC', joven: false, portero: false },
    { nombre: 'RUIZ Fabian', pos: 'MC', joven: false, portero: false },
    { nombre: 'GAVI', pos: 'MC', joven: false, portero: false },
    { nombre: 'OLMO Dani', pos: 'DC', joven: false, portero: false },
    { nombre: 'PINO Yeremy', pos: 'DC', joven: false, portero: false },
    { nombre: 'PORRO Pedro', pos: 'DF', joven: false, portero: false },
    { nombre: 'GARCIA Joan', pos: 'PO', joven: false, portero: true },
    { nombre: 'LAPORTE Aymeric', pos: 'DF', joven: false, portero: false },
    { nombre: 'BAENA Alex', pos: 'MC', joven: false, portero: false },
    { nombre: 'RODRI', pos: 'MC', joven: false, portero: false },
    { nombre: 'WILLIAMS Nico', pos: 'DC', joven: false, portero: false },
    { nombre: 'ZUBIMENDI Martin', pos: 'MC', joven: false, portero: false },
    { nombre: 'YAMAL Lamine', pos: 'DC', joven: true, portero: false },
    { nombre: 'PEDRI', pos: 'MC', joven: false, portero: false },
    { nombre: 'OYARZABAL Mikel', pos: 'DC', joven: false, portero: false },
    { nombre: 'CUBARSI Pau', pos: 'DF', joven: true, portero: false },
    { nombre: 'SIMON Unai', pos: 'PO', joven: false, portero: true },
    { nombre: 'CUCURELLA Marc', pos: 'DF', joven: false, portero: false },
    { nombre: 'MUNOZ Victor', pos: 'DC', joven: false, portero: false },
    { nombre: 'IGLESIAS Borja', pos: 'DC', joven: false, portero: false },
  ],
  'Estados Unidos': [
    { nombre: 'TURNER Matt', pos: 'PO', joven: false, portero: true },
    { nombre: 'DEST Sergino', pos: 'DF', joven: false, portero: false },
    { nombre: 'RICHARDS Chris', pos: 'DF', joven: false, portero: false },
    { nombre: 'ADAMS Tyler', pos: 'MC', joven: false, portero: false },
    { nombre: 'ROBINSON Antonee', pos: 'DF', joven: false, portero: false },
    { nombre: 'TRUSTY Auston', pos: 'DF', joven: false, portero: false },
    { nombre: 'REYNA Giovanni', pos: 'MC', joven: false, portero: false },
    { nombre: 'McKENNIE Weston', pos: 'MC', joven: false, portero: false },
    { nombre: 'PEPI Ricardo', pos: 'DC', joven: false, portero: false },
    { nombre: 'PULISIC Christian', pos: 'DC', joven: false, portero: false },
    { nombre: 'AARONSON Brenden', pos: 'DC', joven: false, portero: false },
    { nombre: 'ROBINSON Miles', pos: 'DF', joven: false, portero: false },
    { nombre: 'REAM Tim', pos: 'DF', joven: false, portero: false },
    { nombre: 'BERHALTER Sebastian', pos: 'MC', joven: false, portero: false },
    { nombre: 'ROLDAN Cristian', pos: 'MC', joven: false, portero: false },
    { nombre: 'FREEMAN Alex', pos: 'DF', joven: false, portero: false },
    { nombre: 'TILLMAN Malik', pos: 'MC', joven: false, portero: false },
    { nombre: 'ARFSTEN Max', pos: 'DF', joven: false, portero: false },
    { nombre: 'WRIGHT Haji', pos: 'DC', joven: false, portero: false },
    { nombre: 'BALOGUN Folarin', pos: 'DC', joven: false, portero: false },
    { nombre: 'WEAH Timothy', pos: 'DC', joven: false, portero: false },
    { nombre: 'McKENZIE Mark', pos: 'DF', joven: false, portero: false },
    { nombre: 'SCALLY Joe', pos: 'DF', joven: false, portero: false },
    { nombre: 'FREESE Matt', pos: 'PO', joven: false, portero: true },
    { nombre: 'BRADY Chris', pos: 'PO', joven: false, portero: true },
    { nombre: 'ZENDEJAS Alex', pos: 'DC', joven: false, portero: false },
  ],
  'Francia': [
    { nombre: 'SAMBA Brice', pos: 'PO', joven: false, portero: true },
    { nombre: 'GUSTO Malo', pos: 'DF', joven: false, portero: false },
    { nombre: 'DIGNE Lucas', pos: 'DF', joven: false, portero: false },
    { nombre: 'UPAMECANO Dayot', pos: 'DF', joven: false, portero: false },
    { nombre: 'KOUNDE Jules', pos: 'DF', joven: false, portero: false },
    { nombre: 'KONE Manu', pos: 'MC', joven: false, portero: false },
    { nombre: 'DEMBELE Ousmane', pos: 'DC', joven: false, portero: false },
    { nombre: 'TCHOUAMENI Aurelien', pos: 'MC', joven: false, portero: false },
    { nombre: 'THURAM Marcus', pos: 'DC', joven: false, portero: false },
    { nombre: 'MBAPPE Kylian', pos: 'DC', joven: false, portero: false },
    { nombre: 'OLISE Michael', pos: 'DC', joven: false, portero: false },
    { nombre: 'BARCOLA Bradley', pos: 'DC', joven: false, portero: false },
    { nombre: 'KANTE Ngolo', pos: 'MC', joven: false, portero: false },
    { nombre: 'RABIOT Adrien', pos: 'MC', joven: false, portero: false },
    { nombre: 'KONATE Ibrahima', pos: 'DF', joven: false, portero: false },
    { nombre: 'MAIGNAN Mike', pos: 'PO', joven: false, portero: true },
    { nombre: 'SALIBA William', pos: 'DF', joven: false, portero: false },
    { nombre: 'ZAIRE-EMERY Warren', pos: 'MC', joven: true, portero: false },
    { nombre: 'HERNANDEZ Theo', pos: 'DF', joven: false, portero: false },
    { nombre: 'DOUE Desire', pos: 'DC', joven: false, portero: false },
    { nombre: 'HERNANDEZ Lucas', pos: 'DF', joven: false, portero: false },
    { nombre: 'MATETA Jean-Philippe', pos: 'DC', joven: false, portero: false },
    { nombre: 'RISSER Robin', pos: 'PO', joven: false, portero: true },
    { nombre: 'CHERKI Rayan', pos: 'MC', joven: false, portero: false },
    { nombre: 'AKLIOUCHE Maghnes', pos: 'MC', joven: false, portero: false },
    { nombre: 'LACROIX Maxence', pos: 'DF', joven: false, portero: false },
  ],
  'Ghana': [
    { nombre: 'ZIGI Lawrence', pos: 'PO', joven: false, portero: true },
    { nombre: 'SEIDU Alidu', pos: 'DF', joven: false, portero: false },
    { nombre: 'YIRENKYI Caleb', pos: 'MC', joven: true, portero: false },
    { nombre: 'ADJETEY Jonas', pos: 'DF', joven: false, portero: false },
    { nombre: 'PARTEY Thomas', pos: 'MC', joven: false, portero: false },
    { nombre: 'MUMIN Abdul', pos: 'DF', joven: false, portero: false },
    { nombre: 'ISSAHAKU Fatawu', pos: 'DC', joven: false, portero: false },
    { nombre: 'SIBO Kwasi', pos: 'MC', joven: false, portero: false },
    { nombre: 'AYEW Jordan', pos: 'DC', joven: false, portero: false },
    { nombre: 'THOMAS-ASANTE Brandon', pos: 'DC', joven: false, portero: false },
    { nombre: 'SEMENYO Antoine', pos: 'MC', joven: false, portero: false },
    { nombre: 'ANANG Joseph', pos: 'PO', joven: false, portero: true },
    { nombre: 'BAAH Christopher', pos: 'DC', joven: false, portero: false },
    { nombre: 'MENSAH Gideon', pos: 'DF', joven: false, portero: false },
    { nombre: 'OWUSU Elisha', pos: 'MC', joven: false, portero: false },
    { nombre: 'ASARE Benjamin', pos: 'PO', joven: false, portero: true },
    { nombre: 'RAHMAN Baba', pos: 'DF', joven: false, portero: false },
    { nombre: 'OPOKU Jerome', pos: 'DF', joven: false, portero: false },
    { nombre: 'WILLIAMS Inaki', pos: 'DC', joven: false, portero: false },
    { nombre: 'BOAKYE Augustine', pos: 'MC', joven: false, portero: false },
    { nombre: 'OPPONG Kojo', pos: 'DF', joven: false, portero: false },
    { nombre: 'SULEMANA Kamaldeen', pos: 'DC', joven: false, portero: false },
    { nombre: 'LUCKASSEN Derrick', pos: 'DF', joven: false, portero: false },
    { nombre: 'NUAMAH Ernest', pos: 'DC', joven: false, portero: false },
    { nombre: 'ADU Prince', pos: 'DC', joven: false, portero: false },
    { nombre: 'SENAYA Marvin', pos: 'DF', joven: false, portero: false },
  ],
  'Haití': [
    { nombre: 'PLACIDE Johny', pos: 'PO', joven: false, portero: true },
    { nombre: 'ARCUS Carlens', pos: 'DF', joven: false, portero: false },
    { nombre: 'THERMONCY Keeto', pos: 'DF', joven: true, portero: false },
    { nombre: 'ADE Ricardo', pos: 'DF', joven: false, portero: false },
    { nombre: 'DELCROIX Hannes', pos: 'DF', joven: false, portero: false },
    { nombre: 'SAINTE Carl', pos: 'MC', joven: false, portero: false },
    { nombre: 'ETIENNE Derrick', pos: 'DC', joven: false, portero: false },
    { nombre: 'EXPERIENCE Martin', pos: 'DF', joven: false, portero: false },
    { nombre: 'NAZON Duckens', pos: 'DC', joven: false, portero: false },
    { nombre: 'BELLEGARDE Jean-Ricner', pos: 'MC', joven: false, portero: false },
    { nombre: 'DEEDSON Louicius', pos: 'DC', joven: false, portero: false },
    { nombre: 'PIERRE Alexandre', pos: 'PO', joven: false, portero: true },
    { nombre: 'LACROIX Markhus', pos: 'DF', joven: false, portero: false },
    { nombre: 'PIERRE Leverton', pos: 'MC', joven: false, portero: false },
    { nombre: 'PROVIDENCE Ruben', pos: 'DC', joven: false, portero: false },
    { nombre: 'JOSEPH Lenny', pos: 'DC', joven: false, portero: false },
    { nombre: 'JEAN JACQUES Danley', pos: 'MC', joven: false, portero: false },
    { nombre: 'ISIDOR Wilson', pos: 'DC', joven: false, portero: false },
    { nombre: 'FORTUNE Yassin', pos: 'DC', joven: false, portero: false },
    { nombre: 'PIERROT Frantzdy', pos: 'DC', joven: false, portero: false },
    { nombre: 'CASIMIR Josue', pos: 'DC', joven: false, portero: false },
    { nombre: 'DUVERNE Jean-Kevin', pos: 'DF', joven: false, portero: false },
    { nombre: 'DUVERGER Josue', pos: 'PO', joven: false, portero: true },
    { nombre: 'PAUGAIN Wilguens', pos: 'DF', joven: false, portero: false },
    { nombre: 'SIMON Dominique', pos: 'MC', joven: false, portero: false },
    { nombre: 'PIERRE Woodensky', pos: 'MC', joven: false, portero: false },
  ],
  'Inglaterra': [
    { nombre: 'PICKFORD Jordan', pos: 'PO', joven: false, portero: true },
    { nombre: 'KONSA Ezri', pos: 'DF', joven: false, portero: false },
    { nombre: 'OREILLY Nico', pos: 'DF', joven: false, portero: false },
    { nombre: 'RICE Declan', pos: 'MC', joven: false, portero: false },
    { nombre: 'STONES John', pos: 'DF', joven: false, portero: false },
    { nombre: 'GUEHI Marc', pos: 'DF', joven: false, portero: false },
    { nombre: 'SAKA Bukayo', pos: 'DC', joven: false, portero: false },
    { nombre: 'ANDERSON Elliot', pos: 'MC', joven: false, portero: false },
    { nombre: 'KANE Harry', pos: 'DC', joven: false, portero: false },
    { nombre: 'BELLINGHAM Jude', pos: 'MC', joven: false, portero: false },
    { nombre: 'RASHFORD Marcus', pos: 'DC', joven: false, portero: false },
    { nombre: 'LIVRAMENTO Tino', pos: 'DF', joven: false, portero: false },
    { nombre: 'HENDERSON Dean', pos: 'PO', joven: false, portero: true },
    { nombre: 'HENDERSON Jordan', pos: 'MC', joven: false, portero: false },
    { nombre: 'BURN Dan', pos: 'DF', joven: false, portero: false },
    { nombre: 'MAINOO Kobbie', pos: 'MC', joven: false, portero: false },
    { nombre: 'ROGERS Morgan', pos: 'MC', joven: false, portero: false },
    { nombre: 'GORDON Anthony', pos: 'DC', joven: false, portero: false },
    { nombre: 'WATKINS Ollie', pos: 'DC', joven: false, portero: false },
    { nombre: 'MADUEKE Noni', pos: 'DC', joven: false, portero: false },
    { nombre: 'EZE Eberechi', pos: 'MC', joven: false, portero: false },
    { nombre: 'TONEY Ivan', pos: 'DC', joven: false, portero: false },
    { nombre: 'TRAFFORD James', pos: 'PO', joven: false, portero: true },
    { nombre: 'JAMES Reece', pos: 'DF', joven: false, portero: false },
    { nombre: 'SPENCE Djed', pos: 'DF', joven: false, portero: false },
    { nombre: 'QUANSAH Jarell', pos: 'DF', joven: false, portero: false },
  ],
  'Irak': [
    { nombre: 'FAHAD TALIB', pos: 'PO', joven: false, portero: true },
    { nombre: 'REBIN GHAREEB', pos: 'DF', joven: false, portero: false },
    { nombre: 'HUSSEIN ALI', pos: 'DF', joven: false, portero: false },
    { nombre: 'ZAID TAHSEEN', pos: 'DF', joven: false, portero: false },
    { nombre: 'AKAM HASHIM', pos: 'DF', joven: false, portero: false },
    { nombre: 'MUNAF YOUNUS', pos: 'DF', joven: false, portero: false },
    { nombre: 'YOUSSEF AMYN', pos: 'MC', joven: false, portero: false },
    { nombre: 'IBRAHIM BAYESH', pos: 'MC', joven: false, portero: false },
    { nombre: 'ALI ALHAMADI', pos: 'DC', joven: false, portero: false },
    { nombre: 'MOHANAD ALI', pos: 'DC', joven: false, portero: false },
    { nombre: 'AHMED QASIM', pos: 'DC', joven: false, portero: false },
    { nombre: 'JALAL HASSAN', pos: 'PO', joven: false, portero: true },
    { nombre: 'ALI YOUSIF', pos: 'DC', joven: false, portero: false },
    { nombre: 'ZIDANE IQBAL', pos: 'MC', joven: false, portero: false },
    { nombre: 'AHMED YAHYA', pos: 'DF', joven: false, portero: false },
    { nombre: 'AMIR ALAMMARI', pos: 'MC', joven: false, portero: false },
    { nombre: 'ALI JASIM', pos: 'DC', joven: false, portero: false },
    { nombre: 'AYMEN HUSSEIN', pos: 'DC', joven: false, portero: false },
    { nombre: 'KEVIN YAKOB', pos: 'MC', joven: false, portero: false },
    { nombre: 'AIMAR SHER', pos: 'MC', joven: false, portero: false },
    { nombre: 'MARKO FARJI', pos: 'DC', joven: false, portero: false },
    { nombre: 'AHMED BASIL', pos: 'PO', joven: false, portero: true },
    { nombre: 'MERCHAS DOSKI', pos: 'DF', joven: false, portero: false },
    { nombre: 'ZAID ISMAEL', pos: 'MC', joven: false, portero: false },
    { nombre: 'MUSTAFA SAADOON', pos: 'DF', joven: false, portero: false },
    { nombre: 'FRANS PUTROS', pos: 'DF', joven: false, portero: false },
  ],
  'Irán': [
    { nombre: 'BEIRANVAND Alireza', pos: 'PO', joven: false, portero: true },
    { nombre: 'HARDANI Saleh', pos: 'DF', joven: false, portero: false },
    { nombre: 'HAJISAFI Ehsan', pos: 'DF', joven: false, portero: false },
    { nombre: 'KHALILZADEH Shoja', pos: 'DF', joven: false, portero: false },
    { nombre: 'MOHAMMADI Milad', pos: 'DF', joven: false, portero: false },
    { nombre: 'EZATOLAHI Saeid', pos: 'MC', joven: false, portero: false },
    { nombre: 'JAHANBAKHSH Alireza', pos: 'MC', joven: false, portero: false },
    { nombre: 'MOHEBBI Mohammad', pos: 'MC', joven: false, portero: false },
    { nombre: 'TAREMI Mehdi', pos: 'DC', joven: false, portero: false },
    { nombre: 'GHAYEDI Mehdi', pos: 'DC', joven: false, portero: false },
    { nombre: 'ALIPOUR Ali', pos: 'DC', joven: false, portero: false },
    { nombre: 'NIAZMAND Payam', pos: 'PO', joven: false, portero: true },
    { nombre: 'KANANI Hossein', pos: 'DF', joven: false, portero: false },
    { nombre: 'GHODDOS Saman', pos: 'MC', joven: false, portero: false },
    { nombre: 'CHESHMI Roozbeh', pos: 'MC', joven: false, portero: false },
    { nombre: 'TORABI Mehdi', pos: 'MC', joven: false, portero: false },
    { nombre: 'YOUSEFI Arya', pos: 'DF', joven: false, portero: false },
    { nombre: 'HOSSEINZADEH Amirhossein', pos: 'DC', joven: false, portero: false },
    { nombre: 'NEMATI Ali', pos: 'DF', joven: false, portero: false },
    { nombre: 'MOGHANLOO Shahriyar', pos: 'DC', joven: false, portero: false },
    { nombre: 'GHORBANI Mohammad', pos: 'MC', joven: false, portero: false },
    { nombre: 'HOSSEINI Hossein', pos: 'PO', joven: false, portero: true },
    { nombre: 'REZAEIAN Ramin', pos: 'DF', joven: false, portero: false },
    { nombre: 'DARGAHI Dennis', pos: 'DC', joven: false, portero: false },
    { nombre: 'IRI Danial', pos: 'DF', joven: false, portero: false },
    { nombre: 'RAZAGHINIA Amirmohammad', pos: 'MC', joven: true, portero: false },
  ],
  'Japón': [
    { nombre: 'SUZUKI Zion', pos: 'PO', joven: false, portero: true },
    { nombre: 'SUGAWARA Yukinari', pos: 'DF', joven: false, portero: false },
    { nombre: 'TANIGUCHI Shogo', pos: 'DF', joven: false, portero: false },
    { nombre: 'ITAKURA Kou', pos: 'DF', joven: false, portero: false },
    { nombre: 'NAGATOMO Yuto', pos: 'DF', joven: false, portero: false },
    { nombre: 'ENDO Wataru', pos: 'MC', joven: false, portero: false },
    { nombre: 'TANAKA Ao', pos: 'MC', joven: false, portero: false },
    { nombre: 'KUBO Takefusa', pos: 'MC', joven: false, portero: false },
    { nombre: 'GOTO Keisuke', pos: 'DC', joven: false, portero: false },
    { nombre: 'DOAN Ritsu', pos: 'MC', joven: false, portero: false },
    { nombre: 'MAEDA Daizen', pos: 'MC', joven: false, portero: false },
    { nombre: 'OSAKO Keisuke', pos: 'PO', joven: false, portero: true },
    { nombre: 'NAKAMURA Keito', pos: 'MC', joven: false, portero: false },
    { nombre: 'ITO Junya', pos: 'MC', joven: false, portero: false },
    { nombre: 'KAMADA Daichi', pos: 'MC', joven: false, portero: false },
    { nombre: 'WATANABE Tsuyoshi', pos: 'DF', joven: false, portero: false },
    { nombre: 'SUZUKI Yuito', pos: 'MC', joven: false, portero: false },
    { nombre: 'UEDA Ayase', pos: 'DC', joven: false, portero: false },
    { nombre: 'OGAWA Koki', pos: 'DC', joven: false, portero: false },
    { nombre: 'SEKO Ayumu', pos: 'DF', joven: false, portero: false },
    { nombre: 'ITO Hiroki', pos: 'DF', joven: false, portero: false },
    { nombre: 'TOMIYASU Takehiro', pos: 'DF', joven: false, portero: false },
    { nombre: 'HAYAKAWA Tomoki', pos: 'PO', joven: false, portero: true },
    { nombre: 'SANO Kaishu', pos: 'MC', joven: false, portero: false },
    { nombre: 'SUZUKI Junnosuke', pos: 'DF', joven: false, portero: false },
    { nombre: 'SHIOGAI Kento', pos: 'DC', joven: false, portero: false },
  ],
  'Jordania': [
    { nombre: 'YAZEED ABULAILA', pos: 'PO', joven: false, portero: true },
    { nombre: 'MOHAMMAD ABUHASHEESH', pos: 'DF', joven: false, portero: false },
    { nombre: 'ABDALLAH NASIB', pos: 'DF', joven: false, portero: false },
    { nombre: 'HUSAM ABUDAHAB', pos: 'DF', joven: false, portero: false },
    { nombre: 'YAZAN ALARAB', pos: 'DF', joven: false, portero: false },
    { nombre: 'AMER JAMOUS', pos: 'MC', joven: false, portero: false },
    { nombre: 'MOHAMMAD ABUZRAIQ', pos: 'DC', joven: false, portero: false },
    { nombre: 'NOOR ALRAWABDEH', pos: 'MC', joven: false, portero: false },
    { nombre: 'ALI OLWAN', pos: 'DC', joven: false, portero: false },
    { nombre: 'MOUSA ALTAMARI', pos: 'DC', joven: false, portero: false },
    { nombre: 'ODEH FAKHOURY', pos: 'DC', joven: true, portero: false },
    { nombre: 'NOUR BANIATEYAH', pos: 'PO', joven: false, portero: true },
    { nombre: 'MAHMOUD ALMARDI', pos: 'DC', joven: false, portero: false },
    { nombre: 'RAJAEI AYED', pos: 'MC', joven: false, portero: false },
    { nombre: 'IBRAHIM SADEH', pos: 'MC', joven: false, portero: false },
    { nombre: 'MOHAMMAD ABUALNADI', pos: 'DF', joven: false, portero: false },
    { nombre: 'SALEEM OBAID', pos: 'DF', joven: false, portero: false },
    { nombre: 'IBRAHIM SABRA', pos: 'DC', joven: true, portero: false },
    { nombre: 'SAED ALROSAN', pos: 'DF', joven: false, portero: false },
    { nombre: 'MOHANNAD ABUTAHA', pos: 'MC', joven: false, portero: false },
    { nombre: 'NIZAR ALRASHDAN', pos: 'MC', joven: false, portero: false },
    { nombre: 'ABDALLAH ALFAKHORI', pos: 'PO', joven: false, portero: true },
    { nombre: 'EHSAN HADDAD', pos: 'DF', joven: false, portero: false },
    { nombre: 'ALI AZAIZEH', pos: 'DC', joven: false, portero: false },
    { nombre: 'MOHAMMAD ALDAOUD', pos: 'MC', joven: false, portero: false },
    { nombre: 'ANAS BADAWI', pos: 'DF', joven: false, portero: false },
  ],
  'Marruecos': [
    { nombre: 'BOUNOU Yassine', pos: 'PO', joven: false, portero: true },
    { nombre: 'HAKIMI Achraf', pos: 'DF', joven: false, portero: false },
    { nombre: 'MAZRAOUI Noussair', pos: 'DF', joven: false, portero: false },
    { nombre: 'AMRABAT Sofyan', pos: 'MC', joven: false, portero: false },
    { nombre: 'AGUERD Nayef', pos: 'DF', joven: false, portero: false },
    { nombre: 'BOUADDI Ayyoub', pos: 'MC', joven: true, portero: false },
    { nombre: 'TALBI Chemsdine', pos: 'MC', joven: false, portero: false },
    { nombre: 'OUNAHI Azzedine', pos: 'MC', joven: false, portero: false },
    { nombre: 'RAHIMI Souane', pos: 'DC', joven: false, portero: false },
    { nombre: 'DIAZ Brahim', pos: 'DC', joven: false, portero: false },
    { nombre: 'SAIBARI Ismael', pos: 'MC', joven: false, portero: false },
    { nombre: 'EL KAJOUI Munir', pos: 'PO', joven: false, portero: true },
    { nombre: 'EL OUAHDI Zakaria', pos: 'DF', joven: false, portero: false },
    { nombre: 'DIOP Issa', pos: 'DF', joven: false, portero: false },
    { nombre: 'EL MOURABET Samir', pos: 'MC', joven: true, portero: false },
    { nombre: 'YASSINE Gessime', pos: 'MC', joven: true, portero: false },
    { nombre: 'EZZALZOULI Abde', pos: 'DC', joven: false, portero: false },
    { nombre: 'RIAD Chadi', pos: 'DF', joven: false, portero: false },
    { nombre: 'BELAMMARI Youssef', pos: 'DF', joven: false, portero: false },
    { nombre: 'EL KAABI Ayoub', pos: 'DC', joven: false, portero: false },
    { nombre: 'AMAIMOUNI Ayoube', pos: 'DC', joven: false, portero: false },
    { nombre: 'TAGNAOUTI Ahmed Reda', pos: 'PO', joven: false, portero: true },
    { nombre: 'EL KHANNOUSS Bilal', pos: 'MC', joven: false, portero: false },
    { nombre: 'EL AYNAOUI Neil', pos: 'MC', joven: false, portero: false },
    { nombre: 'HALHAL Redouane', pos: 'DF', joven: false, portero: false },
    { nombre: 'SALAH EDDINE Anass', pos: 'DF', joven: false, portero: false },
  ],
  'México': [
    { nombre: 'RANGEL Raul', pos: 'PO', joven: false, portero: true },
    { nombre: 'SANCHEZ Jorge', pos: 'DF', joven: false, portero: false },
    { nombre: 'MONTES Cesar', pos: 'DF', joven: false, portero: false },
    { nombre: 'ALVAREZ Edson', pos: 'DF', joven: false, portero: false },
    { nombre: 'VASQUEZ Johan', pos: 'DF', joven: false, portero: false },
    { nombre: 'LIRA Erik', pos: 'MC', joven: false, portero: false },
    { nombre: 'ROMO Luis', pos: 'MC', joven: false, portero: false },
    { nombre: 'FIDALGO Alvaro', pos: 'MC', joven: false, portero: false },
    { nombre: 'JIMENEZ Raul', pos: 'DC', joven: false, portero: false },
    { nombre: 'VEGA Alexis', pos: 'DC', joven: false, portero: false },
    { nombre: 'GIMENEZ Santiago', pos: 'DC', joven: false, portero: false },
    { nombre: 'ACEVEDO Carlos', pos: 'PO', joven: false, portero: true },
    { nombre: 'OCHOA Guillermo', pos: 'PO', joven: false, portero: true },
    { nombre: 'GONZALEZ Armando', pos: 'DC', joven: false, portero: false },
    { nombre: 'REYES Israel', pos: 'DF', joven: false, portero: false },
    { nombre: 'QUINONES Julian', pos: 'DC', joven: false, portero: false },
    { nombre: 'PINEDA Orbelin', pos: 'MC', joven: false, portero: false },
    { nombre: 'VARGAS Obed', pos: 'MC', joven: true, portero: false },
    { nombre: 'MORA Gilberto', pos: 'MC', joven: true, portero: false },
    { nombre: 'CHAVEZ Mateo', pos: 'DF', joven: false, portero: false },
    { nombre: 'HUERTA Cesar', pos: 'DC', joven: false, portero: false },
    { nombre: 'MARTINEZ Guillermo', pos: 'DC', joven: false, portero: false },
    { nombre: 'GALLARDO Jesus', pos: 'DF', joven: false, portero: false },
    { nombre: 'CHAVEZ Luis', pos: 'MC', joven: false, portero: false },
    { nombre: 'ALVARADO Roberto', pos: 'DC', joven: false, portero: false },
    { nombre: 'GUTIERREZ Brian', pos: 'MC', joven: false, portero: false },
  ],
  'Noruega': [
    { nombre: 'NYLAND Orjan', pos: 'PO', joven: false, portero: true },
    { nombre: 'THORSBY Morten', pos: 'MC', joven: false, portero: false },
    { nombre: 'AJER Kristoffer', pos: 'DF', joven: false, portero: false },
    { nombre: 'OSTIGARD Leo', pos: 'DF', joven: false, portero: false },
    { nombre: 'MOLLER WOLFE David', pos: 'DF', joven: false, portero: false },
    { nombre: 'BERG Patrick', pos: 'MC', joven: false, portero: false },
    { nombre: 'SORLOTH Alexander', pos: 'DC', joven: false, portero: false },
    { nombre: 'BERGE Sander', pos: 'MC', joven: false, portero: false },
    { nombre: 'HAALAND Erling', pos: 'DC', joven: false, portero: false },
    { nombre: 'ODEGAARD Martin', pos: 'MC', joven: false, portero: false },
    { nombre: 'STRAND LARSEN Jorgen', pos: 'DC', joven: false, portero: false },
    { nombre: 'TANGVIK Sander', pos: 'PO', joven: false, portero: true },
    { nombre: 'SELVIK Egil', pos: 'PO', joven: false, portero: true },
    { nombre: 'AURSNES Fredrik', pos: 'MC', joven: false, portero: false },
    { nombre: 'BJORKAN Fredrik', pos: 'DF', joven: false, portero: false },
    { nombre: 'HOLMGREN PEDERSEN Marcus', pos: 'DF', joven: false, portero: false },
    { nombre: 'HEGGEM Torbjorn', pos: 'DF', joven: false, portero: false },
    { nombre: 'THORSTVEDT Kristian', pos: 'MC', joven: false, portero: false },
    { nombre: 'AASGAARD Thelo', pos: 'MC', joven: false, portero: false },
    { nombre: 'NUSA Antonio', pos: 'DC', joven: false, portero: false },
    { nombre: 'SCHJELDERUP Andreas', pos: 'MC', joven: false, portero: false },
    { nombre: 'BOBB Oscar', pos: 'MC', joven: false, portero: false },
    { nombre: 'HAUGE Jens Petter', pos: 'MC', joven: false, portero: false },
    { nombre: 'LANGAS Sondre', pos: 'DF', joven: false, portero: false },
    { nombre: 'FALCHENER Henrik', pos: 'DF', joven: false, portero: false },
    { nombre: 'RYERSON Julian', pos: 'DC', joven: false, portero: false },
  ],
  'Nueva Zelanda': [
    { nombre: 'CROCOMBE Max', pos: 'PO', joven: false, portero: true },
    { nombre: 'PAYNE Tim', pos: 'DF', joven: false, portero: false },
    { nombre: 'DE VRIES Francis', pos: 'DF', joven: false, portero: false },
    { nombre: 'BINDON Tyler', pos: 'DF', joven: false, portero: false },
    { nombre: 'BOXALL Michael', pos: 'DF', joven: false, portero: false },
    { nombre: 'BELL Joe', pos: 'MC', joven: false, portero: false },
    { nombre: 'GARBETT Matthew', pos: 'MC', joven: false, portero: false },
    { nombre: 'STAMENIC Marko', pos: 'MC', joven: false, portero: false },
    { nombre: 'WOOD Chris', pos: 'DC', joven: false, portero: false },
    { nombre: 'SINGH Sarpreet', pos: 'MC', joven: false, portero: false },
    { nombre: 'JUST Elijah', pos: 'MC', joven: false, portero: false },
    { nombre: 'PAULSEN Alex', pos: 'PO', joven: false, portero: true },
    { nombre: 'CACACE Liberato', pos: 'DF', joven: false, portero: false },
    { nombre: 'RUFER Alex', pos: 'MC', joven: false, portero: false },
    { nombre: 'PIJNAKER Nando', pos: 'DF', joven: false, portero: false },
    { nombre: 'SURMAN Finn', pos: 'DF', joven: false, portero: false },
    { nombre: 'BARBAROUSES Kosta', pos: 'DC', joven: false, portero: false },
    { nombre: 'WAINE Ben', pos: 'DC', joven: false, portero: false },
    { nombre: 'OLD Ben', pos: 'MC', joven: false, portero: false },
    { nombre: 'McCOWATT Callum', pos: 'MC', joven: false, portero: false },
    { nombre: 'RANDALL Jesse', pos: 'DC', joven: false, portero: false },
    { nombre: 'WOUD Michael', pos: 'PO', joven: false, portero: true },
    { nombre: 'THOMAS Ryan', pos: 'MC', joven: false, portero: false },
    { nombre: 'ELLIOT Callan', pos: 'DF', joven: false, portero: false },
    { nombre: 'BAYLISS Lachlan', pos: 'MC', joven: false, portero: false },
    { nombre: 'SMITH Tommy', pos: 'DF', joven: false, portero: false },
  ],
  'Panamá': [
    { nombre: 'MEJIA Luis', pos: 'PO', joven: false, portero: true },
    { nombre: 'BLACKMAN Cesar', pos: 'DF', joven: false, portero: false },
    { nombre: 'CORDOBA Jose', pos: 'DF', joven: false, portero: false },
    { nombre: 'ESCOBAR Fidel', pos: 'DF', joven: false, portero: false },
    { nombre: 'FARINA Edgardo', pos: 'DF', joven: false, portero: false },
    { nombre: 'MARTINEZ Cristian', pos: 'MC', joven: false, portero: false },
    { nombre: 'RODRIGUEZ Jose Luis', pos: 'MC', joven: false, portero: false },
    { nombre: 'CARRASQUILLA Adalberto', pos: 'MC', joven: false, portero: false },
    { nombre: 'RODRIGUEZ Tomas', pos: 'DC', joven: false, portero: false },
    { nombre: 'DIAZ Ismael', pos: 'MC', joven: false, portero: false },
    { nombre: 'BARCENAS Edgar', pos: 'MC', joven: false, portero: false },
    { nombre: 'SAMUDIO Cesar', pos: 'PO', joven: false, portero: true },
    { nombre: 'RAMOS Jiovany', pos: 'DF', joven: false, portero: false },
    { nombre: 'HARVEY Carlos', pos: 'DF', joven: false, portero: false },
    { nombre: 'DAVIS Eric', pos: 'DF', joven: false, portero: false },
    { nombre: 'ANDRADE Andres', pos: 'DF', joven: false, portero: false },
    { nombre: 'FAJARDO Jose', pos: 'DC', joven: false, portero: false },
    { nombre: 'WATERMAN Cecilio', pos: 'DC', joven: false, portero: false },
    { nombre: 'QUINTERO Alberto', pos: 'MC', joven: false, portero: false },
    { nombre: 'GODOY Anibal', pos: 'MC', joven: false, portero: false },
    { nombre: 'YANIS Cesar', pos: 'MC', joven: false, portero: false },
    { nombre: 'MOSQUERA Orlando', pos: 'PO', joven: false, portero: true },
    { nombre: 'MURILLO Amir', pos: 'DF', joven: false, portero: false },
    { nombre: 'LONDONO Azarias', pos: 'DC', joven: false, portero: false },
    { nombre: 'MILLER Roderick', pos: 'DF', joven: false, portero: false },
    { nombre: 'GUTIERREZ Jorge', pos: 'DF', joven: false, portero: false },
  ],
  'Paraguay': [
    { nombre: 'FERNANDEZ Gatito', pos: 'PO', joven: false, portero: true },
    { nombre: 'VELAZQUEZ Gustavo', pos: 'DF', joven: false, portero: false },
    { nombre: 'ALDERETE Omar', pos: 'DF', joven: false, portero: false },
    { nombre: 'CACERES Juan Jose', pos: 'DF', joven: false, portero: false },
    { nombre: 'BALBUENA Fabian', pos: 'DF', joven: false, portero: false },
    { nombre: 'ALONSO Junior', pos: 'DF', joven: false, portero: false },
    { nombre: 'SOSA Ramon', pos: 'MC', joven: false, portero: false },
    { nombre: 'GOMEZ Diego', pos: 'MC', joven: false, portero: false },
    { nombre: 'SANABRIA Antonio', pos: 'DC', joven: false, portero: false },
    { nombre: 'ALMIRON Miguel', pos: 'MC', joven: false, portero: false },
    { nombre: 'MAURICIO', pos: 'MC', joven: false, portero: false },
    { nombre: 'GILL Orlando', pos: 'PO', joven: false, portero: true },
    { nombre: 'CANALE Jose', pos: 'DF', joven: false, portero: false },
    { nombre: 'CUBAS Andres', pos: 'MC', joven: false, portero: false },
    { nombre: 'GOMEZ Gustavo', pos: 'DF', joven: false, portero: false },
    { nombre: 'BOBADILLA Damian', pos: 'MC', joven: false, portero: false },
    { nombre: 'ROMERO GAMARRA Alejandro', pos: 'DC', joven: false, portero: false },
    { nombre: 'ARCE Alex', pos: 'DC', joven: false, portero: false },
    { nombre: 'ENCISO Julio', pos: 'DC', joven: false, portero: false },
    { nombre: 'OJEDA Braian', pos: 'MC', joven: false, portero: false },
    { nombre: 'AVALOS Gabriel', pos: 'DC', joven: false, portero: false },
    { nombre: 'OLVEIRA Gaston', pos: 'PO', joven: false, portero: true },
    { nombre: 'GALARZA Matias', pos: 'MC', joven: false, portero: false },
    { nombre: 'CABALLERO Gustavo', pos: 'MC', joven: false, portero: false },
    { nombre: 'PITTA Isidro', pos: 'DC', joven: false, portero: false },
    { nombre: 'MAIDANA Alexandro', pos: 'DF', joven: true, portero: false },
  ],
  'Países Bajos': [
    { nombre: 'VERBRUGGEN Bart', pos: 'PO', joven: false, portero: true },
    { nombre: 'TIMBER Jurrien', pos: 'DF', joven: false, portero: false },
    { nombre: 'DE ROON Marten', pos: 'MC', joven: false, portero: false },
    { nombre: 'VAN DIJK Virgil', pos: 'DF', joven: false, portero: false },
    { nombre: 'AKE Nathan', pos: 'DF', joven: false, portero: false },
    { nombre: 'VAN HECKE Jan Paul', pos: 'DF', joven: false, portero: false },
    { nombre: 'KLUIVERT Justin', pos: 'MC', joven: false, portero: false },
    { nombre: 'GRAVENBERCH Ryan', pos: 'MC', joven: false, portero: false },
    { nombre: 'WEGHORST Wout', pos: 'DC', joven: false, portero: false },
    { nombre: 'DEPAY Memphis', pos: 'DC', joven: false, portero: false },
    { nombre: 'GAKPO Cody', pos: 'DC', joven: false, portero: false },
    { nombre: 'WIEFFER Mats', pos: 'DF', joven: false, portero: false },
    { nombre: 'ROEFS Robin', pos: 'PO', joven: false, portero: true },
    { nombre: 'REIJNDERS Tijjani', pos: 'MC', joven: false, portero: false },
    { nombre: 'VAN DE VEN Micky', pos: 'DF', joven: false, portero: false },
    { nombre: 'TIL Guus', pos: 'MC', joven: false, portero: false },
    { nombre: 'LANG Noa', pos: 'DC', joven: false, portero: false },
    { nombre: 'MALEN Donyell', pos: 'DC', joven: false, portero: false },
    { nombre: 'BROBBEY Brian', pos: 'DC', joven: false, portero: false },
    { nombre: 'KOOPMEINERS Teun', pos: 'MC', joven: false, portero: false },
    { nombre: 'DE JONG Frenkie', pos: 'MC', joven: false, portero: false },
    { nombre: 'DUMFRIES Denzel', pos: 'DF', joven: false, portero: false },
    { nombre: 'FLEKKEN Mark', pos: 'PO', joven: false, portero: true },
    { nombre: 'SUMMERVILLE Crysencio', pos: 'DC', joven: false, portero: false },
    { nombre: 'HATO Jorrel', pos: 'DF', joven: true, portero: false },
    { nombre: 'TIMBER Quinten', pos: 'MC', joven: false, portero: false },
  ],
  'Portugal': [
    { nombre: 'DIOGO COSTA', pos: 'PO', joven: false, portero: true },
    { nombre: 'NELSON SEMEDO', pos: 'DF', joven: false, portero: false },
    { nombre: 'RUBEN DIAS', pos: 'DF', joven: false, portero: false },
    { nombre: 'TOMAS ARAUJO', pos: 'DF', joven: false, portero: false },
    { nombre: 'DIOGO DALOT', pos: 'DF', joven: false, portero: false },
    { nombre: 'MATHEUS NUNES', pos: 'MC', joven: false, portero: false },
    { nombre: 'CRISTIANO RONALDO', pos: 'DC', joven: false, portero: false },
    { nombre: 'BRUNO FERNANDES', pos: 'MC', joven: false, portero: false },
    { nombre: 'GONCALO RAMOS', pos: 'DC', joven: false, portero: false },
    { nombre: 'BERNARDO SILVA', pos: 'MC', joven: false, portero: false },
    { nombre: 'JOAO FELIX', pos: 'DC', joven: false, portero: false },
    { nombre: 'JOSE SA', pos: 'PO', joven: false, portero: true },
    { nombre: 'RENATO VEIGA', pos: 'DF', joven: false, portero: false },
    { nombre: 'GONCALO INACIO', pos: 'DF', joven: false, portero: false },
    { nombre: 'JOAO NEVES', pos: 'MC', joven: false, portero: false },
    { nombre: 'FRANCISCO TRINCAO', pos: 'DC', joven: false, portero: false },
    { nombre: 'RAFAEL LEAO', pos: 'DC', joven: false, portero: false },
    { nombre: 'PEDRO NETO', pos: 'DC', joven: false, portero: false },
    { nombre: 'GONCALO GUEDES', pos: 'DC', joven: false, portero: false },
    { nombre: 'JOAO CANCELO', pos: 'DF', joven: false, portero: false },
    { nombre: 'RUBEN NEVES', pos: 'MC', joven: false, portero: false },
    { nombre: 'RUI SILVA', pos: 'PO', joven: false, portero: true },
    { nombre: 'VITINHA', pos: 'MC', joven: false, portero: false },
    { nombre: 'SAMU COSTA', pos: 'DF', joven: false, portero: false },
    { nombre: 'NUNO MENDES', pos: 'DF', joven: false, portero: false },
    { nombre: 'FRANCISCO CONCEICAO', pos: 'DC', joven: false, portero: false },
  ],
  'RD Congo': [
    { nombre: 'MPASI Lionel', pos: 'PO', joven: false, portero: true },
    { nombre: 'WAN-BISSAKA Aaron', pos: 'DF', joven: false, portero: false },
    { nombre: 'KAPUADI Steve', pos: 'DF', joven: false, portero: false },
    { nombre: 'TUANZEBE Axel', pos: 'DF', joven: false, portero: false },
    { nombre: 'BATUBINSIKA Dylan', pos: 'DF', joven: false, portero: false },
    { nombre: 'MUKAU Ngalayel', pos: 'MC', joven: false, portero: false },
    { nombre: 'MBUKU Nathanael', pos: 'MC', joven: false, portero: false },
    { nombre: 'MOUTOUSSAMY Samuel', pos: 'MC', joven: false, portero: false },
    { nombre: 'CIPENGA Brian', pos: 'DC', joven: false, portero: false },
    { nombre: 'BONGONDA Theo', pos: 'MC', joven: false, portero: false },
    { nombre: 'KAKUTA Gael', pos: 'DC', joven: false, portero: false },
    { nombre: 'KAYEMBE Joris', pos: 'DF', joven: false, portero: false },
    { nombre: 'ELIA Meschack', pos: 'DC', joven: false, portero: false },
    { nombre: 'SADIKI Noah', pos: 'MC', joven: false, portero: false },
    { nombre: 'TSHIBOLA Aaron', pos: 'MC', joven: false, portero: false },
    { nombre: 'FAYULU Timothy', pos: 'PO', joven: false, portero: true },
    { nombre: 'BAKAMBU Cedric', pos: 'DC', joven: false, portero: false },
    { nombre: 'PICKEL Charles', pos: 'MC', joven: false, portero: false },
    { nombre: 'MAYELE Fiston', pos: 'DC', joven: false, portero: false },
    { nombre: 'WISSA Yoane', pos: 'DC', joven: false, portero: false },
    { nombre: 'EPOLO Matthieu', pos: 'PO', joven: false, portero: true },
    { nombre: 'MBEMBA Chancel', pos: 'DF', joven: false, portero: false },
    { nombre: 'BANZA Simon', pos: 'DC', joven: false, portero: false },
    { nombre: 'KALULU Gedeon', pos: 'DF', joven: false, portero: false },
    { nombre: 'KAYEMBE Edo', pos: 'MC', joven: false, portero: false },
    { nombre: 'MASUAKU Arthur', pos: 'DF', joven: false, portero: false },
  ],
  'República Checa': [
    { nombre: 'KOVAR Matej', pos: 'PO', joven: false, portero: true },
    { nombre: 'ZIMA David', pos: 'DF', joven: false, portero: false },
    { nombre: 'HOLES Tomas', pos: 'DF', joven: false, portero: false },
    { nombre: 'HRANAC Robin', pos: 'DF', joven: false, portero: false },
    { nombre: 'COUFAL Vladimir', pos: 'DF', joven: false, portero: false },
    { nombre: 'CHALOUPEK Stepan', pos: 'DF', joven: false, portero: false },
    { nombre: 'KREJCI Ladislav', pos: 'DF', joven: false, portero: false },
    { nombre: 'DARIDA Vladimir', pos: 'MC', joven: false, portero: false },
    { nombre: 'HLOZEK Adam', pos: 'DC', joven: false, portero: false },
    { nombre: 'SCHICK Patrik', pos: 'DC', joven: false, portero: false },
    { nombre: 'KUCHTA Jan', pos: 'DC', joven: false, portero: false },
    { nombre: 'CERV Lukas', pos: 'MC', joven: false, portero: false },
    { nombre: 'CHYTIL Mojmir', pos: 'DC', joven: false, portero: false },
    { nombre: 'JURASEK David', pos: 'DF', joven: false, portero: false },
    { nombre: 'SULC Pavel', pos: 'DC', joven: false, portero: false },
    { nombre: 'STANEK Jindrich', pos: 'PO', joven: false, portero: true },
    { nombre: 'PROVOD Lukas', pos: 'MC', joven: false, portero: false },
    { nombre: 'SADILEK Michal', pos: 'MC', joven: false, portero: false },
    { nombre: 'CHORY Tomas', pos: 'DC', joven: false, portero: false },
    { nombre: 'ZELENY Jaroslav', pos: 'DF', joven: false, portero: false },
    { nombre: 'DOUDERA David', pos: 'DF', joven: false, portero: false },
    { nombre: 'SOUCEK Tomas', pos: 'MC', joven: false, portero: false },
    { nombre: 'HORNICEK Lukas', pos: 'PO', joven: false, portero: true },
    { nombre: 'SOJKA Alexandr', pos: 'MC', joven: false, portero: false },
    { nombre: 'SOCHUREK Hugo', pos: 'MC', joven: true, portero: false },
    { nombre: 'VISINSKY Denis', pos: 'DC', joven: false, portero: false },
  ],
  'Senegal': [
    { nombre: 'DIOUF Yehvann', pos: 'PO', joven: false, portero: true },
    { nombre: 'SARR Mamadou', pos: 'DF', joven: true, portero: false },
    { nombre: 'KOULIBALY Kalidou', pos: 'DF', joven: false, portero: false },
    { nombre: 'SECK Abdoulaye', pos: 'DF', joven: false, portero: false },
    { nombre: 'GUEYE Idrissa', pos: 'MC', joven: false, portero: false },
    { nombre: 'CISS Pathe', pos: 'MC', joven: false, portero: false },
    { nombre: 'DIAO Assane', pos: 'DC', joven: true, portero: false },
    { nombre: 'CAMARA Lamine', pos: 'MC', joven: false, portero: false },
    { nombre: 'DIENG Bamba', pos: 'DC', joven: false, portero: false },
    { nombre: 'MANE Sadio', pos: 'DC', joven: false, portero: false },
    { nombre: 'JACKSON Nicolas', pos: 'DC', joven: false, portero: false },
    { nombre: 'NDIAYE Cherif', pos: 'DC', joven: false, portero: false },
    { nombre: 'NDIAYE Iliman', pos: 'DC', joven: false, portero: false },
    { nombre: 'JAKOBS Ismail', pos: 'DF', joven: false, portero: false },
    { nombre: 'DIATTA Krepin', pos: 'DF', joven: false, portero: false },
    { nombre: 'MENDY Edouard', pos: 'PO', joven: false, portero: true },
    { nombre: 'SARR Pape Matar', pos: 'MC', joven: false, portero: false },
    { nombre: 'SARR Ismaila', pos: 'DC', joven: false, portero: false },
    { nombre: 'NIAKHATE Moussa', pos: 'DF', joven: false, portero: false },
    { nombre: 'MBAYE Ibrahim', pos: 'DC', joven: true, portero: false },
    { nombre: 'DIARRA Habib', pos: 'MC', joven: false, portero: false },
    { nombre: 'NDIAYE Bara', pos: 'MC', joven: true, portero: false },
    { nombre: 'DIAW Mory', pos: 'PO', joven: false, portero: true },
    { nombre: 'MENDY Antoine', pos: 'DF', joven: false, portero: false },
    { nombre: 'DIOUF El Hadji', pos: 'DF', joven: false, portero: false },
    { nombre: 'GUEYE Pape', pos: 'MC', joven: false, portero: false },
  ],
  'Sudáfrica': [
    { nombre: 'WILLIAMS Ronwen', pos: 'PO', joven: false, portero: true },
    { nombre: 'MATULUDI Thabang', pos: 'DF', joven: false, portero: false },
    { nombre: 'NDAMANE Khulumani', pos: 'DF', joven: false, portero: false },
    { nombre: 'MOKOENA Teboho', pos: 'MC', joven: false, portero: false },
    { nombre: 'MBATHA Thalente', pos: 'MC', joven: false, portero: false },
    { nombre: 'MODIBA Aubrey', pos: 'DF', joven: false, portero: false },
    { nombre: 'APPOLLIS Oswin', pos: 'DC', joven: false, portero: false },
    { nombre: 'MOREMI Tshepang', pos: 'DC', joven: false, portero: false },
    { nombre: 'FOSTER Lyle', pos: 'DC', joven: false, portero: false },
    { nombre: 'MOFOKENG Relebohile', pos: 'DC', joven: false, portero: false },
    { nombre: 'ZWANE Themba', pos: 'MC', joven: false, portero: false },
    { nombre: 'MASEKO Thapelo', pos: 'DC', joven: false, portero: false },
    { nombre: 'SITHOLE Sphephelo', pos: 'MC', joven: false, portero: false },
    { nombre: 'MBOKAZI Mbekezeli', pos: 'DF', joven: true, portero: false },
    { nombre: 'RAYNERS Iqraam', pos: 'DC', joven: false, portero: false },
    { nombre: 'CHAINE Sipho', pos: 'PO', joven: false, portero: true },
    { nombre: 'MAKGOPA Evidence', pos: 'DC', joven: false, portero: false },
    { nombre: 'KABINI Samukele', pos: 'DF', joven: false, portero: false },
    { nombre: 'SIBISI Nkosinathi', pos: 'DF', joven: false, portero: false },
    { nombre: 'MUDAU Khuliso', pos: 'DF', joven: false, portero: false },
    { nombre: 'OKON Ime', pos: 'DF', joven: false, portero: false },
    { nombre: 'GOSS Ricardo', pos: 'PO', joven: false, portero: true },
    { nombre: 'ADAMS Jayden', pos: 'MC', joven: false, portero: false },
    { nombre: 'MAKHANYA Olwethu', pos: 'DF', joven: false, portero: false },
    { nombre: 'SEBELEBELE Kamogelo', pos: 'DC', joven: false, portero: false },
    { nombre: 'CROSS Bradley', pos: 'DF', joven: false, portero: false },
  ],
  'Suecia': [
    { nombre: 'WIDELL ZETTERSTROM Jacob', pos: 'PO', joven: false, portero: true },
    { nombre: 'LAGERBIELKE Gustaf', pos: 'DF', joven: false, portero: false },
    { nombre: 'LINDELOF Victor', pos: 'DF', joven: false, portero: false },
    { nombre: 'HIEN Isak', pos: 'DF', joven: false, portero: false },
    { nombre: 'GUDMUNDSSON Gabriel', pos: 'DF', joven: false, portero: false },
    { nombre: 'JOHANSSON Herman', pos: 'DF', joven: false, portero: false },
    { nombre: 'BERGVALL Lucas', pos: 'MC', joven: true, portero: false },
    { nombre: 'SVENSSON Daniel', pos: 'DF', joven: false, portero: false },
    { nombre: 'ISAK Alexander', pos: 'DC', joven: false, portero: false },
    { nombre: 'NYGREN Benjamin', pos: 'MC', joven: false, portero: false },
    { nombre: 'ELANGA Anthony', pos: 'DC', joven: false, portero: false },
    { nombre: 'JOHANSSON Viktor', pos: 'PO', joven: false, portero: true },
    { nombre: 'SEMA Ken', pos: 'MC', joven: false, portero: false },
    { nombre: 'EKDAL Hjalmar', pos: 'DF', joven: false, portero: false },
    { nombre: 'STARFELT Carl', pos: 'DF', joven: false, portero: false },
    { nombre: 'KARLSTROM Jesper', pos: 'MC', joven: false, portero: false },
    { nombre: 'GYOKERES Viktor', pos: 'DC', joven: false, portero: false },
    { nombre: 'AYARI Yasin', pos: 'MC', joven: false, portero: false },
    { nombre: 'SVANBERG Mattias', pos: 'MC', joven: false, portero: false },
    { nombre: 'SMITH Eric', pos: 'DF', joven: false, portero: false },
    { nombre: 'BERNHARDSSON Alexander', pos: 'DF', joven: false, portero: false },
    { nombre: 'ZENELI Besfort', pos: 'MC', joven: false, portero: false },
    { nombre: 'NORDFELDT Kristoffer', pos: 'PO', joven: false, portero: true },
    { nombre: 'STROUD Elliot', pos: 'DF', joven: false, portero: false },
    { nombre: 'NILSSON Gustaf', pos: 'DC', joven: false, portero: false },
    { nombre: 'ALI Taha', pos: 'DC', joven: false, portero: false },
  ],
  'Suiza': [
    { nombre: 'KOBEL Gregor', pos: 'PO', joven: false, portero: true },
    { nombre: 'MUHEIM Miro', pos: 'DF', joven: false, portero: false },
    { nombre: 'WIDMER Silvan', pos: 'DF', joven: false, portero: false },
    { nombre: 'ELVEDI Nico', pos: 'DF', joven: false, portero: false },
    { nombre: 'AKANJI Manuel', pos: 'DF', joven: false, portero: false },
    { nombre: 'ZAKARIA Denis', pos: 'MC', joven: false, portero: false },
    { nombre: 'EMBOLO Breel', pos: 'DC', joven: false, portero: false },
    { nombre: 'FREULER Remo', pos: 'MC', joven: false, portero: false },
    { nombre: 'MANZAMBI Johan', pos: 'MC', joven: true, portero: false },
    { nombre: 'XHAKA Granit', pos: 'MC', joven: false, portero: false },
    { nombre: 'NDOYE Dan', pos: 'DC', joven: false, portero: false },
    { nombre: 'MVOGO Yvon', pos: 'PO', joven: false, portero: true },
    { nombre: 'RODRIGUEZ Ricardo', pos: 'DF', joven: false, portero: false },
    { nombre: 'JASHARI Ardon', pos: 'MC', joven: false, portero: false },
    { nombre: 'SOW Djibril', pos: 'MC', joven: false, portero: false },
    { nombre: 'FASSNACHT Christian', pos: 'DC', joven: false, portero: false },
    { nombre: 'VARGAS Ruben', pos: 'DC', joven: false, portero: false },
    { nombre: 'COEMERT Eray', pos: 'DF', joven: false, portero: false },
    { nombre: 'OKAFOR Noah', pos: 'DC', joven: false, portero: false },
    { nombre: 'AEBISCHER Michel', pos: 'MC', joven: false, portero: false },
    { nombre: 'KELLER Marvin', pos: 'PO', joven: false, portero: true },
    { nombre: 'RIEDER Fabian', pos: 'MC', joven: false, portero: false },
    { nombre: 'AMDOUNI Zeki', pos: 'DC', joven: false, portero: false },
    { nombre: 'AMENDA Aurele', pos: 'DF', joven: false, portero: false },
    { nombre: 'JAQUEZ Luca', pos: 'DF', joven: false, portero: false },
    { nombre: 'ITTEN Cedric', pos: 'DC', joven: false, portero: false },
  ],
  'Turquía': [
    { nombre: 'GUNOK Mert', pos: 'PO', joven: false, portero: true },
    { nombre: 'CELIK Zeki', pos: 'DF', joven: false, portero: false },
    { nombre: 'DEMIRAL Merih', pos: 'DF', joven: false, portero: false },
    { nombre: 'SOYUNCU Caglar', pos: 'DF', joven: false, portero: false },
    { nombre: 'OZCAN Salih', pos: 'MC', joven: false, portero: false },
    { nombre: 'KOKCU Orkun', pos: 'MC', joven: false, portero: false },
    { nombre: 'AKTURKOGLU Kerem', pos: 'DC', joven: false, portero: false },
    { nombre: 'GULER Arda', pos: 'DC', joven: false, portero: false },
    { nombre: 'GUL Deniz', pos: 'DC', joven: false, portero: false },
    { nombre: 'CALHANOGLU Hakan', pos: 'MC', joven: false, portero: false },
    { nombre: 'YILDIZ Kenan', pos: 'DC', joven: false, portero: false },
    { nombre: 'BAYINDIR Altay', pos: 'PO', joven: false, portero: true },
    { nombre: 'ELMALI Eren', pos: 'DF', joven: false, portero: false },
    { nombre: 'BARDAKCI Abdulkerim', pos: 'DF', joven: false, portero: false },
    { nombre: 'KABAK Ozan', pos: 'DF', joven: false, portero: false },
    { nombre: 'YUKSEK Ismail', pos: 'MC', joven: false, portero: false },
    { nombre: 'KAHVECI Irfan Can', pos: 'DC', joven: false, portero: false },
    { nombre: 'MULDUR Mert', pos: 'DF', joven: false, portero: false },
    { nombre: 'AKGUN Yunus', pos: 'DC', joven: false, portero: false },
    { nombre: 'KADIOGLU Ferdi', pos: 'DF', joven: false, portero: false },
    { nombre: 'YILMAZ Baris Alper', pos: 'DC', joven: false, portero: false },
    { nombre: 'AYHAN Kaan', pos: 'MC', joven: false, portero: false },
    { nombre: 'CAKIR Ugurcan', pos: 'PO', joven: false, portero: true },
    { nombre: 'AYDIN Oguz', pos: 'DC', joven: false, portero: false },
    { nombre: 'AKAYDIN Samet', pos: 'DF', joven: false, portero: false },
    { nombre: 'UZUN Can', pos: 'DC', joven: true, portero: false },
  ],
  'Túnez': [
    { nombre: 'CHAMAKH Mouhib', pos: 'PO', joven: false, portero: true },
    { nombre: 'ABDI Ali', pos: 'DF', joven: false, portero: false },
    { nombre: 'TALBI Montassar', pos: 'DF', joven: false, portero: false },
    { nombre: 'REKIK Omar', pos: 'DF', joven: false, portero: false },
    { nombre: 'AROUS Adam', pos: 'DF', joven: false, portero: false },
    { nombre: 'BRONN Dylan', pos: 'DF', joven: false, portero: false },
    { nombre: 'ACHOURI Elias', pos: 'DC', joven: false, portero: false },
    { nombre: 'SAAD Elias', pos: 'DC', joven: false, portero: false },
    { nombre: 'MASTOURI Hazem', pos: 'DC', joven: false, portero: false },
    { nombre: 'MEJBRI Hannibal', pos: 'MC', joven: false, portero: false },
    { nombre: 'GHARBI Ismael', pos: 'MC', joven: false, portero: false },
    { nombre: 'BEN OUANES Mortadha', pos: 'DF', joven: false, portero: false },
    { nombre: 'KHEDIRA Rani', pos: 'MC', joven: false, portero: false },
    { nombre: 'AYARI Khalil', pos: 'MC', joven: false, portero: false },
    { nombre: 'HADJ MAHMOUD Mohamed', pos: 'MC', joven: false, portero: false },
    { nombre: 'DAHMEN Aymen', pos: 'PO', joven: false, portero: true },
    { nombre: 'SKHIRI Ellyes', pos: 'MC', joven: false, portero: false },
    { nombre: 'ELLOUMI Rayan', pos: 'DC', joven: true, portero: false },
    { nombre: 'CHAOUAT Firas', pos: 'DC', joven: false, portero: false },
    { nombre: 'VALERY Yan', pos: 'DF', joven: false, portero: false },
    { nombre: 'BEN HMIDA Mohamed Amine', pos: 'DF', joven: false, portero: false },
    { nombre: 'BEN HESSEN Sabri', pos: 'PO', joven: false, portero: true },
    { nombre: 'NEFFATI Moutaz', pos: 'DF', joven: false, portero: false },
    { nombre: 'CHIKHAOUI Raed', pos: 'DF', joven: false, portero: false },
    { nombre: 'SLIMANE Anis', pos: 'MC', joven: false, portero: false },
    { nombre: 'TOUNEKTI Sebastian', pos: 'MC', joven: false, portero: false },
  ],
  'Uruguay': [
    { nombre: 'ROCHET Sergio', pos: 'PO', joven: false, portero: true },
    { nombre: 'GIMENEZ Jose Maria', pos: 'DF', joven: false, portero: false },
    { nombre: 'CACERES Sebastian', pos: 'DF', joven: false, portero: false },
    { nombre: 'ARAUJO Ronald', pos: 'DF', joven: false, portero: false },
    { nombre: 'UGARTE Manuel', pos: 'MC', joven: false, portero: false },
    { nombre: 'BENTANCUR Rodrigo', pos: 'MC', joven: false, portero: false },
    { nombre: 'DE LA CRUZ Nicolas', pos: 'MC', joven: false, portero: false },
    { nombre: 'VALVERDE Federico', pos: 'MC', joven: false, portero: false },
    { nombre: 'NUNEZ Darwin', pos: 'DC', joven: false, portero: false },
    { nombre: 'DE ARRASCAETA Giorgian', pos: 'MC', joven: false, portero: false },
    { nombre: 'PELLISTRI Facundo', pos: 'DC', joven: false, portero: false },
    { nombre: 'MELE Santiago', pos: 'PO', joven: false, portero: true },
    { nombre: 'VARELA Guillermo', pos: 'DF', joven: false, portero: false },
    { nombre: 'CANOBBIO Agustin', pos: 'MC', joven: false, portero: false },
    { nombre: 'MARTINEZ Emiliano', pos: 'MC', joven: false, portero: false },
    { nombre: 'OLIVERA Mathias', pos: 'DF', joven: false, portero: false },
    { nombre: 'VINA Matias', pos: 'DF', joven: false, portero: false },
    { nombre: 'RODRIGUEZ Brian', pos: 'DC', joven: false, portero: false },
    { nombre: 'AGUIRRE Rodrigo', pos: 'DC', joven: false, portero: false },
    { nombre: 'ARAUJO Maxi', pos: 'MC', joven: false, portero: false },
    { nombre: 'VINAS Federico', pos: 'DC', joven: false, portero: false },
    { nombre: 'PIQUEREZ Joaquin', pos: 'MC', joven: false, portero: false },
    { nombre: 'MUSLERA Fernando', pos: 'PO', joven: false, portero: true },
    { nombre: 'BUENO Santiago', pos: 'DF', joven: false, portero: false },
    { nombre: 'SANABRIA Juan Manuel', pos: 'MC', joven: false, portero: false },
    { nombre: 'ZALAZAR Rodrigo', pos: 'MC', joven: false, portero: false },
  ],
  'Uzbekistán': [
    { nombre: 'YUSUPOV Utkir', pos: 'PO', joven: false, portero: true },
    { nombre: 'KHUSANOV Abdukodir', pos: 'DF', joven: false, portero: false },
    { nombre: 'ALIJONOV Khojiakbar', pos: 'DF', joven: false, portero: false },
    { nombre: 'SAYFIEV Farrukh', pos: 'DF', joven: false, portero: false },
    { nombre: 'ASHURMATOV Rustam', pos: 'DF', joven: false, portero: false },
    { nombre: 'MOZGOVOY Akmal', pos: 'MC', joven: false, portero: false },
    { nombre: 'SHUKUROV Otabek', pos: 'MC', joven: false, portero: false },
    { nombre: 'ISKANDEROV Jamshid', pos: 'MC', joven: false, portero: false },
    { nombre: 'XAMROBEKOV Odiljon', pos: 'MC', joven: false, portero: false },
    { nombre: 'MASHARIPOV Jaloliddin', pos: 'MC', joven: false, portero: false },
    { nombre: 'URUNOV Oston', pos: 'MC', joven: false, portero: false },
    { nombre: 'NEMATOV Abduvohid', pos: 'PO', joven: false, portero: true },
    { nombre: 'NASRULLAEV Sherzod', pos: 'DF', joven: false, portero: false },
    { nombre: 'SHOMURODOV Eldor', pos: 'DC', joven: false, portero: false },
    { nombre: 'ESHMURODOV Umar', pos: 'DF', joven: false, portero: false },
    { nombre: 'ERGASHEV Botirali', pos: 'PO', joven: false, portero: true },
    { nombre: 'KHAMDAMOV Dostonbek', pos: 'MC', joven: false, portero: false },
    { nombre: 'ABDULLAEV Abdulla', pos: 'DF', joven: false, portero: false },
    { nombre: 'GANIEV Azizjon', pos: 'MC', joven: false, portero: false },
    { nombre: 'AMONOV Azizbek', pos: 'DC', joven: false, portero: false },
    { nombre: 'SERGEEV Igor', pos: 'DC', joven: false, portero: false },
    { nombre: 'FAYZULLAEV Abbosbek', pos: 'MC', joven: false, portero: false },
    { nombre: 'ESANOV Sherzod', pos: 'MC', joven: false, portero: false },
    { nombre: 'KARIMOV Behruzjon', pos: 'DF', joven: true, portero: false },
    { nombre: 'ULMASALIYEV Avazbek', pos: 'DF', joven: false, portero: false },
    { nombre: 'UROZOV Jakhongir', pos: 'DF', joven: false, portero: false },
  ],
}

export function getPorteros(seleccion) {
  return (JUGADORES[seleccion] || []).filter(j => j.portero)
}

export function getJovenes(seleccion) {
  return (JUGADORES[seleccion] || []).filter(j => j.joven)
}

export function getTodos(seleccion) {
  return JUGADORES[seleccion] || []
}
